USE [LEMIR_Stage]
GO
--
DELETE FROM [dbo].[FAC_CONTACT]
GO
DELETE FROM [dbo].[FAC_LOCATION]
GO
DELETE FROM [dbo].[FAC_ADDRESS]
GO
DELETE FROM [dbo].[FAC_EMAIL]
GO
DELETE FROM [dbo].[FAC_TELEPHONIC]
GO
DELETE FROM [dbo].[SYS_GEO_COORDINATE]
GO
DELETE FROM [dbo].[SYS_PHYSICAL_LOCATION]
GO
DELETE FROM [dbo].[SYS_CONTACT]
GO
DELETE FROM [dbo].[SYS_ADDRESS]
GO
DELETE FROM [dbo].[SYS_EMAIL]
GO
DELETE FROM [dbo].[SYS_TELEPHONIC]
GO
DELETE FROM [dbo].[SYS_CONTACT_ADDRESS]
GO
DELETE FROM [dbo].[SYS_CONTACT_TELEPHONIC]
GO
DELETE FROM [dbo].[SYS_CONTACT_EMAIL]
GO
DELETE FROM [dbo].[FAC_FACILITY]
GO