USE [GovOnline_LEMIR]
GO
DELETE FROM [dbo].[SYS_DISPOSAL_HISTORY]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [dbo].[SYS_DISPOSAL]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [GOV].[SUB_SUBMISSION]
WHERE [CREATED_BY] = 'EPDMIG SWT';
--
USE [GovOnline_GEOS]
GO
DELETE FROM [GOV].[SUB_SUBMISSION]
WHERE [CREATED_BY] = 'EPDMIG SWT';
