USE [GovOnline_LEMIR]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYS_DISPOSAL_HISTORY_SYS_DISPOSAL]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL_HISTORY]'))
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SYS_DISPOSAL]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYS_DISPOSAL_HISTORY_SUB_FEE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL_HISTORY]'))
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SUB_FEE]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL_HISTORY_2942E3E3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [DF__SYS_DISPOSAL_HISTORY_2942E3E3]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL_HISTORY__UPDAT__275A9B71]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__UPDAT__275A9B71]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL_HISTORY__CREAT__284EBFAA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__CREAT__284EBFAA]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL_HISTORY_CREAT__26667738]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [DF__SYS_DISPOSAL_HISTORY_CREAT__26667738]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL_HISTORY__257252FF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] DROP CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__257252FF]
END
GO

/****** Object:  Table [dbo].[SYS_DISPOSAL_HISTORY]    Script Date: 4/23/2019 11:47:01 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL_HISTORY]') AND type in (N'U'))
DROP TABLE [dbo].[SYS_DISPOSAL_HISTORY]
GO

/****** Object:  Table [dbo].[SYS_DISPOSAL_HISTORY]    Script Date: 4/23/2019 11:47:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SYS_DISPOSAL_HISTORY](
	[SYS_DISPOSAL_HISTORY_RID] [int] NOT NULL,
	[SYS_DISPOSAL_RID] [int] NOT NULL,
	[ORIGINAL_DISPOSAL_AMOUNT] [decimal](12, 2) NOT NULL,
	[REVISED_DISPOSAL_AMOUNT] [decimal](12, 2) NOT NULL,
	[ORIGINAL_RECYCLED_AMOUNT] [decimal](12, 2) NOT NULL,
	[REVISED_RECYCLED_AMOUNT] [decimal](12, 2) NOT NULL,
	[COMMENT_TEXT] [varchar](4000) NULL,
	[SUB_FEE_RID] [int] NULL,
	[SYN_DATE] [datetime] NULL,
	[SENT_BY] [varchar](100) NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
	[REVISED_DATE] [datetime] NULL,
	[REVISED_BY] [varchar](100) NULL,
	[BATCH_TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_SYS_DISPOSAL_HISTORY] PRIMARY KEY CLUSTERED 
(
	[SYS_DISPOSAL_HISTORY_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__257252FF]  DEFAULT ('A') FOR [STATUS_CD]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY_CREAT__26667738]  DEFAULT ('SYSTEM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__CREAT__284EBFAA]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__UPDAT__275A9B71]  DEFAULT ('SYSTEM') FOR [UPDATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY_2942E3E3]  DEFAULT (getdate()) FOR [UPDATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SUB_FEE] FOREIGN KEY([SUB_FEE_RID])
REFERENCES [GOV].[SUB_FEE] ([SUB_FEE_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] CHECK CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SUB_FEE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SYS_DISPOSAL] FOREIGN KEY([SYS_DISPOSAL_RID])
REFERENCES [dbo].[SYS_DISPOSAL] ([SYS_DISPOSAL_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] CHECK CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SYS_DISPOSAL]
GO


w