USE [LEMIR_Stage_Out]
GO
INSERT INTO [dbo].[$1_GEOS_SYS_ADDRESS]
       ([ADDRESS_RID],
        [ADDRESS_LINE1],
        [ADDRESS_LINE2],
        [CITY_NAME],
        [PROVINCE_NAME],
        [STATE_RID],
        [COUNTY_RID],
        [COUNTRY_RID],
        [DISTRICT_NAME],
        [STREET_DISTRICT_NAME],
        [ZIP_CD],
        [ZIP_SUFFIX_CD],
        [STATUS_CD],
        [CREATED_BY],
        [UPDATED_BY],
        [CREATED_DATE],
        [UPDATED_DATE],
        [ADDRESS_TYPE_RID],
        [TRIBE_RID],
        [QUAD_CD],
        [ADDRESS_NAME],
        [APT_NO],
        [BLOCK_NO],
        [LOT_NO],
        [QUAL_NO],
        [PROPERTY_OWNER],
        [GAPDES_ADDRESS_ID])
SELECT [ADDRESS_RID],
       [ADDRESS_LINE1],
       [ADDRESS_LINE2],
       [CITY_NAME],
       [PROVINCE_NAME],
       [STATE_RID],
       [COUNTY_RID],
       [COUNTRY_RID],
       [DISTRICT_NAME],
       [STREET_DISTRICT_NAME],
       [ZIP_CD],
       [ZIP_SUFFIX_CD],
       [STATUS_CD],
       [CREATED_BY],
       [UPDATED_BY],
       [CREATED_DATE],
       [UPDATED_DATE],
       [ADDRESS_TYPE_RID],
       [TRIBE_RID],
       [QUAD_CD],
       [ADDRESS_NAME],
       [APT_NO],
       [BLOCK_NO],
       [LOT_NO],
       [QUAL_NO],
       [PROPERTY_OWNER],
       [GAPDES_ADDRESS_ID]
FROM [LEMIR_Stage].[dbo].[$1_GEOS_SYS_ADDRESS]
GO



