USE [GovOnline_LEMIR]
GO

/****** Object:  Table [dbo].[FAC_ENV_PROGRAM_ATTACHMENT]    Script Date: 1/17/2019 2:55:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT](
	[FAC_ENV_PROGRAM_RID] [int] NOT NULL,
	[ATTACHMENT_RID] [int] NOT NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](0) NOT NULL,
	[UPDATED_DATE] [datetime2](0) NOT NULL,
 CONSTRAINT [FAC_ENV_PROGRAM_ATTACHMENT_PK] PRIMARY KEY CLUSTERED 
(
	[ATTACHMENT_RID] ASC,
	[FAC_ENV_PROGRAM_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] ADD  DEFAULT ('A') FOR [STATUS_CD]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] ADD  DEFAULT ('SYS') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] ADD  DEFAULT ('SYS') FOR [UPDATED_BY]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] ADD  DEFAULT (sysdatetime()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] ADD  DEFAULT (sysdatetime()) FOR [UPDATED_DATE]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK1_FAC_ENV_PROGRAM_ATTACHMENT] FOREIGN KEY([FAC_ENV_PROGRAM_RID])
REFERENCES [dbo].[FAC_ENV_PROGRAM] ([FAC_ENV_PROGRAM_RID])
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] CHECK CONSTRAINT [FK1_FAC_ENV_PROGRAM_ATTACHMENT]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT]  WITH CHECK ADD  CONSTRAINT [FK2_FAC_ENV_PROGRAM_ATTACHMENT] FOREIGN KEY([ATTACHMENT_RID])
REFERENCES [dbo].[SYS_ATTACHMENT] ([ATTACHMENT_RID])
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_ATTACHMENT] CHECK CONSTRAINT [FK2_FAC_ENV_PROGRAM_ATTACHMENT]
GO


USE [GovOnline_LEMIR]
GO

/****** Object:  Table [dbo].[FAC_ENV_PROGRAM_COMPLIANCE]    Script Date: 1/17/2019 2:55:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FAC_ENV_PROGRAM_COMPLIANCE](
	[FAC_ENV_PROGRAM_COMPLIANCE_RID] [int] NOT NULL,
	[FAC_ENV_PROGRAM_RID] [int] NOT NULL,
	[PRE_STATUS] [varchar](50) NULL,
	[NEW_STATUS] [varchar](50) NOT NULL,
	[REVISED_BY] [varchar](100) NOT NULL,
	[REVISED_DATE] [datetime] NOT NULL,
	[COMMENTS] [varchar](8000) NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_FAC_ENV_PROGRAM_COMPLIANCE] PRIMARY KEY CLUSTERED 
(
	[FAC_ENV_PROGRAM_COMPLIANCE_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_COMPLIANCE]  WITH CHECK ADD  CONSTRAINT [FK_FAC_ENV_PROGRAM_COMPLIANCE_FAC_ENV_PROGRAM] FOREIGN KEY([FAC_ENV_PROGRAM_RID])
REFERENCES [dbo].[FAC_ENV_PROGRAM] ([FAC_ENV_PROGRAM_RID])
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_COMPLIANCE] CHECK CONSTRAINT [FK_FAC_ENV_PROGRAM_COMPLIANCE_FAC_ENV_PROGRAM]
GO


USE [GovOnline_LEMIR]
GO

/****** Object:  Table [dbo].[FAC_ENV_PROGRAM_MILESTONE]    Script Date: 1/17/2019 2:55:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FAC_ENV_PROGRAM_MILESTONE](
	[FAC_ENV_PROGRAM_MILESTONE_RID] [int] NOT NULL,
	[FAC_ENV_PROGRAM_RID] [int] NOT NULL,
	[MILESTONE_DESC] [varchar](200) NULL,
	[DUE_DATE] [datetime] NULL,
	[COMPLETED_IND] [varchar](10) NULL,
	[COMMENTS] [varchar](8000) NULL,
	[ACTION] [varchar](200) NULL,
	[ACTION_DATE] [datetime] NULL,
	[ACTION_BY] [varchar](100) NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_FAC_ENV_PROGRAM_MILESTONE] PRIMARY KEY CLUSTERED 
(
	[FAC_ENV_PROGRAM_MILESTONE_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_MILESTONE]  WITH CHECK ADD  CONSTRAINT [FK_FAC_ENV_PROGRAM_MILESTONE_FAC_ENV_PROGRAM] FOREIGN KEY([FAC_ENV_PROGRAM_RID])
REFERENCES [dbo].[FAC_ENV_PROGRAM] ([FAC_ENV_PROGRAM_RID])
GO

ALTER TABLE [dbo].[FAC_ENV_PROGRAM_MILESTONE] CHECK CONSTRAINT [FK_FAC_ENV_PROGRAM_MILESTONE_FAC_ENV_PROGRAM]
GO


