--
--
--
SELECT DISTINCT
       [MFI].[MainPermitNumber],
       [MFI].[FacilityName],
       --[FAMAIN].[ID],
       [FAMAIN].[COUNTY],
       [FAMAIN].[PERMIT NUMBER],
       [MFI].[OperationStatus],
       [MFI].[FacilityType],
       [MFI].[FacilityTypeDescription],
       [MFI].[FacilityStartDate],
       [MFI].[FacilityAmendedDate],
       [MFI].[FacilityEndDate],
       [MFI].[FacilityAddress],
       [MFI].[City],
       [MFI].[State],
       [MFI].[ZipCode],
       [MFI].[County],
       [MFI].[Region],
       [MFI].[TotalAcreage],
       [MFI].[UsableAcreage],
       [MFI].[LocationDescription],
       [MFI].[Comments],
       [MFI].[EPAID],
       [MFI].[Private],
       [MFI].[Dominion],
       [MFI].[HSIRequested],
       [MFI].[HSIListed],
       [MFI].[ProposedCapacity(CY)],
       [MFI].[PermittedCapacity(CY)],
       [MFI].[PermitIssueDate],
       [MFI].[DateCeasedAcceptingWaste],
       [MFI].[DateClosureCertificate Issued],
       [MFI].[PC/CPeriod],
       [MFI].[LCSystem],
       [MFI].[VE],
       [MFI].[Liner],
       [MFI].[LinerType],
       [MFI].[OtherLinerType],
       [MFI].[SIC],
       [MFI].[GWSystemInstalled],
       [MFI].[MethaneSystemInstalled],
       [MFI].[GWReleaseConfirmed],
       [MFI].[UnderDrainSystemInstalled],
       [MFI].[UDSystemReleaseConfirmed],
       [MFI].[MailingAddress],
       [MFI].[MailingCity],
       [MFI].[MailingState],
       [MFI].[MailingZipCode],
       [MFI].[PostCLosureCareReleaseDate],
       [MFI].[LFGasCollectionApproved],
       [MFI].[LandfillGastoEnergyApproved],
       [MFI].[LandfillGasenergyUsedfor],
       [MFI].[Materials Recovery Facility (MRF) Approved?],
       [MFI].[Type of Waste(s) Processed by MRF],
       [MFI].[Composting Operation Approved?],
       [MFI].[Type of Material (s) Composted],
       [MFI].[Combined Landfills with Common GW System Description],
       [MFI].[CDLandfill],
       [MFI].[CDLandfillOperationStatus],
       [MFI].[InertLandfill],
       [MFI].[InertLandfillOperationStatus],
       [MFI].[TransferStation],
       [MFI].[TransferStationOperationStatus]
       --[FAMAIN].[PRIVATE],
       --[FAMAIN].[CA RQD],
       --[FAMAIN].[Type Year],
       --[FAMAIN].[TypeInstrument],
       --[FAMAIN].[InstrumentNo],
       --[FAMAIN].[InstrumentAmountReceived],
       --[FAMAIN].[InstrumentBeginDate],
       --[FAMAIN].[InstrumrntEndDate],
       --[FAMAIN].[InstrumentCovers],
       --[FAMAIN].[CEASEDRECEIVINGWASTEDATE],
       --[FAMAIN].[CLOSURE CERT DATE],
       --[FAMAIN].[FISCAL YEAR END],
       --[FAMAIN].[DATE FA DUE],
       --[FAMAIN].[DATE FA REC'D],
       --[FAMAIN].[DATE FA APPVD],
       --[FAMAIN].[DATE FA REJECT],
       --[FAMAIN].[CL BASE DATE],
       --[FAMAIN].[PC BASE DATE],
       --[FAMAIN].[CA BASE DATE],
       --[FAMAIN].[DISCOUNT],
       --[FAMAIN].[ORIG CL AMT],
       --[FAMAIN].[ORIG PC AMT],
       --[FAMAIN].[CURRENT CL AMT],
       --[FAMAIN].[CURRENT PC AMT],
       --[FAMAIN].[ORIG CA AMT],
       --[FAMAIN].[CURRENT CA AMT],
       --[FAMAIN].[ORIG ASSURED COST],
       --[FAMAIN].[CURRENT ASSURED COST],
       --[FAMAIN].[EPD ENGINEER],
       --[FAMAIN].[IN/OUT COMPL],
       --[FAMAIN].[Received(butnotreviewed)],
       --[FAMAIN].[IN COMPLIANCE?],
       --[FAMAIN].[Comments],
       --[FAMAIN].[InComplianceUntil],
       --[FAMAIN].[FA_Required]
FROM [LandDatabase].[dbo].[MAIN FACILITY INFO] AS [MFI]
     LEFT JOIN [LandDatabase].[dbo].[FA MAIN] AS [FAMAIN] ON [MFI].[MainPermitNumber] = [famain].[PERMIT NUMBER]
--WHERE [FAMAIN].[COUNTY] IS NOT NULL

