
--INSERT INTO [LEMIR_Stage_Out].[GOV].[SUB_PERMIT]
--       ([PERMIT_RID],
--        [SUBMISSION_RID],
--        [SUB_FORM_RID],
--        [PERMIT_NUMBER],
--        [SYS_USER_RID],
--        [SYS_FACILITY_ID],
--        [FACILITY_NAME],
--        [ISSUED_BY],
--        [ISSUED_DTTM],
--        [EFFECTIVE_DTTM],
--        [EXPIRATION_DTTM],
--        [STATUS_CD],
--        [COMMENTS],
--        [CREATED_DTTM],
--        [CREATED_BY],
--        [UPDATED_DTTM],
--        [UPDATED_BY],
--        [TRANSFER_TO],
--        [PERMIT_STATUS_RID],
--        [PERMIT_TYPE_RID],
--        [PERMIT_DETAIL],
--        [PERMIT_NAME],
--        [REPORT_RID],
--        [NUMBER_SUFFIX],
--        [EXPIRATION_DESC],
--        [BARCODE_IMAGE],
--        [BARCODE_NUMBER],
--        [SUB_PRIOR_APPROVAL_RID],
--        [OBJECT_TYPE],
--        [DESCRIPTION],
--        [APPLICATION_RID],
--        [PERMIT_STAGE_RID],
--        [CONTROL_NUMBER],
--        [EXCHANGE_PERMIT_RID],
--        [OBJECT],
--        [REVISION_NO],
--        [CHECK_OUT_BY],
--        [CHECK_OUT_DATE],
--        [CHECK_OUT_DIRECTORY],
--        [VERSION_NO],
--        [LOCK_IND],
--        [PERMIT_FILE_NAME],
--        [EXTRA_INFO],
--        [PERMIT_FILE_EXT])
SELECT [PERMIT_RID],
       [SUBMISSION_RID],
       [SUB_FORM_RID],
       [PERMIT_NUMBER],
       [SYS_USER_RID],
       [SYS_FACILITY_ID],
       [FACILITY_NAME],
       [ISSUED_BY],
       [ISSUED_DTTM],
       [EFFECTIVE_DTTM],
       [EXPIRATION_DTTM],
       [STATUS_CD],
       [COMMENTS],
       [CREATED_DTTM],
       [CREATED_BY],
       [UPDATED_DTTM],
       [UPDATED_BY],
       [TRANSFER_TO],
       [PERMIT_STATUS_RID],
       [PERMIT_TYPE_RID],
       [PERMIT_DETAIL],
       [PERMIT_NAME],
       [REPORT_RID],
       [NUMBER_SUFFIX],
       [EXPIRATION_DESC],
       [BARCODE_IMAGE],
       [BARCODE_NUMBER],
       [SUB_PRIOR_APPROVAL_RID],
       [OBJECT_TYPE],
       [DESCRIPTION],
       [APPLICATION_RID],
       [PERMIT_STAGE_RID],
       [CONTROL_NUMBER],
       [EXCHANGE_PERMIT_RID],
       [OBJECT],
       [REVISION_NO],
       [CHECK_OUT_BY],
       [CHECK_OUT_DATE],
       [CHECK_OUT_DIRECTORY],
       [VERSION_NO],
       [LOCK_IND],
       [PERMIT_FILE_NAME],
       [EXTRA_INFO],
       [PERMIT_FILE_EXT]
       --[FACILITY_ID_REF]
FROM [LEMIR_Stage].[GOV].[SUB_PERMIT]
WHERE [PERMIT_RID] > 2634680


