

INSERT INTO [LEMIR_Stage_Out].[dbo].[SYS_ADDRESS]
       ([ADDRESS_RID],
        [ADDRESS_LINE1],
        [ADDRESS_LINE2],
        [CITY_NAME],
        [PROVINCE_NAME],
        [STATE_RID],
        [COUNTY_RID],
        [COUNTRY_RID],
        [DISTRICT_NAME],
        [STREET_DISTRICT_NAME],
        [ZIP_CD],
        [ZIP_SUFFIX_CD],
        [STATUS_CD],
        [CREATED_BY],
        [UPDATED_BY],
        [CREATED_DATE],
        [UPDATED_DATE],
        [ADDRESS_TYPE_RID],
        [TRIBE_RID],
        [QUAD_CD],
        [ADDRESS_NAME],
        [APT_NO],
        [BLOCK_NO],
        [LOT_NO],
        [QUAL_NO],
        [PROPERTY_OWNER])
SELECT [ADDRESS_RID],
       [ADDRESS_LINE1],
       [ADDRESS_LINE2],
       [CITY_NAME],
       [PROVINCE_NAME],
       [STATE_RID],
       [COUNTY_RID],
       [COUNTRY_RID],
       [DISTRICT_NAME],
       [STREET_DISTRICT_NAME],
       [ZIP_CD],
       [ZIP_SUFFIX_CD],
       [STATUS_CD],
       [CREATED_BY],
       [UPDATED_BY],
       [CREATED_DATE],
       [UPDATED_DATE],
       [ADDRESS_TYPE_RID],
       [TRIBE_RID],
       [QUAD_CD],
       [ADDRESS_NAME],
       [APT_NO],
       [BLOCK_NO],
       [LOT_NO],
       [QUAL_NO],
       [PROPERTY_OWNER]
       --[FACILITY_ID_REF]
FROM [LEMIR_Stage].[dbo].[SYS_ADDRESS]
WHERE [FACILITY_ID_REF] IN(
                           '037-011D(C&D)',
                           '044-037D(SL)',
                           '095-008D(L)',
                           '056-015D(L)',
                           '021-005D(L)',
                           '138-007D(C&D)',
                           '057-021D(C&D)',
                           '146-015D(MSWL)',
                           '089-020D(L)',
                           '136-017D(C&D)',
                           '033-037D(L)',
                           '038-015D(C&D)',
                           '098-006D(C&D)',
                           '126-010D(C&D)',
                           '155-048D(LI)',
                           '105-012D(L)'
                          )


