

SELECT DISTINCT
       [FF].[FACILITY_RID],
       [SP].[PERMIT_NUMBER],
       [FF].[FACILITY_NAME],
       [FF].[FIS_ID],
       [SP].[FACILITY_NAME],
       [FEP].[AKA_NAME],
       [RRPT].[TYPE_RID],
       [RRPT].[TYPE_CD],
       [RRPT].[TYPE_NAME]
FROM [GovOnline_LEMIR].[dbo].[FAC_FACILITY] AS [FF]
     LEFT JOIN [GovOnline_LEMIR].[GOV].[SUB_PERMIT] AS [SP] ON [ff].[FACILITY_RID] = [SP].[SYS_FACILITY_ID]
     LEFT JOIN [GovOnline_LEMIR].[dbo].[FAC_ENV_PROGRAM] AS [FEP] ON [FF].[FACILITY_RID] = [FEP].[FACILITY_RID]
                                                                     AND [SP].[PERMIT_NUMBER] = [FEP].[FAC_PROGRAM_IDENTIFIER]
     LEFT JOIN [GovOnline_LEMIR].[dbo].[REF_REG_PROGRAM_TYPE] AS [RRPT] ON [FEP].[TYPE_RID] = [RRPT].[TYPE_RID]
WHERE [FEP].[TYPE_RID] IN(10041, 10042, 10043, 10044, 10045, 10046, 10047, 10048, 10049, 10050, 10051, 10052, 10053, 10054, 10055, 10056, 10057, 10058, 10059)
      AND [SP].[PERMIT_NUMBER] NOT LIKE 'PBR%'
      AND [SP].[PERMIT_NUMBER] NOT LIKE '%GN%'
      AND [SP].[PERMIT_NUMBER] NOT LIKE '%BPN%'
      AND [SP].[PERMIT_NUMBER] NOT LIKE '%GW%'
      AND [SP].[PERMIT_NUMBER] LIKE '%-%'
ORDER BY 2