USE [LEMIR_Stage_fixes]
GO
--INSERT INTO [dbo].[PMT_PERMIT_GEOS]
--       ([PERMIT_RID],
--        [PERMIT_NO],
--        [FACILITY_RID],
--        [PERMIT_TYPE_RID],
--        [EFF_DATE],
--        [EXP_DATE],
--        [DRAFT_ISSUE_DATE],
--        [ISSUE_DATE],
--        [REVOKED_DATE],
--        [RENEWAL_DATE],
--        [RENEWAL_REMIND_DATE],
--        [APPROVE_DATE],
--        [APPROVED_BY],
--        [REPORT_FREQUENCY_RID],
--        [PERMIT_STATUS_RID],
--        [PERMIT_STATUS_CHANGE_REASON],
--        [PARENT_PERMIT_RID],
--        [ASSOCIATED_PREVIOUS_PERMIT_RID],
--        [ESUBMISSION_IND],
--        [DEFAULT_DURATION],
--        [DEFAULT_DURATION_UNIT],
--        [STATUS_CD],
--        [CREATED_DATE],
--        [CREATED_BY],
--        [UPDATED_DATE],
--        [UPDATED_BY],
--        [PERMIT_XML],
--        [COMMENT_TEXT],
--        [PERMIT_NAME],
--        [PROGRAM_TYPE_RID],
--        [STATE_PERMIT_ID],
--        [PERMIT_VERSION],
--        [TERMINATE_DATE],
--        [PERMITTEE_NAME],
--        [EXTENDED_EXP_DATE],
--        [AGGREGATED_IND],
--        [NRCCWPI_PERMIT_INSTANCE_ID],
--        [PMT_CONTINUOUS_IND],
--        [PMT_EXTENDED_DATE],
--        [IPACS_PMT_ID],
--        [IPACS_SUBMISSION_RID],
--        [RENEW_PERMIT_IND],
--        [PERMIT_APPLICATION_RID])
SELECT [PERMIT_RID],
       [PERMIT_NO],
       [FACILITY_RID],
       [PERMIT_TYPE_RID],
       [EFF_DATE],
       [EXP_DATE],
       [DRAFT_ISSUE_DATE],
       [ISSUE_DATE],
       [REVOKED_DATE],
       [RENEWAL_DATE],
       [RENEWAL_REMIND_DATE],
       [APPROVE_DATE],
       [APPROVED_BY],
       [REPORT_FREQUENCY_RID],
       [PERMIT_STATUS_RID],
       [PERMIT_STATUS_CHANGE_REASON],
       [PARENT_PERMIT_RID],
       [ASSOCIATED_PREVIOUS_PERMIT_RID],
       [ESUBMISSION_IND],
       [DEFAULT_DURATION],
       [DEFAULT_DURATION_UNIT],
       [STATUS_CD],
       [CREATED_DATE],
       [CREATED_BY],
       [UPDATED_DATE],
       [UPDATED_BY],
       [PERMIT_XML],
       [COMMENT_TEXT],
       [PERMIT_NAME],
       [PROGRAM_TYPE_RID],
       [STATE_PERMIT_ID],
       [PERMIT_VERSION],
       [TERMINATE_DATE],
       [PERMITTEE_NAME],
       [EXTENDED_EXP_DATE],
       [AGGREGATED_IND],
       [NRCCWPI_PERMIT_INSTANCE_ID],
       [PMT_CONTINUOUS_IND],
       [PMT_EXTENDED_DATE],
       [IPACS_PMT_ID],
       [IPACS_SUBMISSION_RID],
       [RENEW_PERMIT_IND],
       [EXCHANGE_PERMIT_RID]
FROM [dbo].[PMT_PERMIT]
GO


