--
DELETE FROM [GovOnline_LEMIR].[dbo].[SYS_DISPOSAL_HISTORY]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [GovOnline_LEMIR].[dbo].[SYS_DISPOSAL]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [GovOnline_LEMIR].[GOV].[SUB_SUBMISSION]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [GovOnline_GEOS].[GOV].[SUB_SUBMISSION]
WHERE [CREATED_BY] = 'EPDMIG SWT'

