
/******************************************************
*** Insert into LEMIR_Stage values for EI "MRF" XML ***
******************************************************/

--
USE [LEMIR_Stage]
GO
--
--INSERT INTO [dbo].[EI_MRF]
--       ([PermitNumber],
--        [EnvIntType],
--        [txtPermitNumber_ID],
--        [txtPermitNumber_VAL],
--        [txtPermitNumber_TAG],
--        [txtPermitNumber_VIS],
--        [txtPermitNumber_HIS],
--        [txtPermitNumber_DES],
--        [txtPermitNumber_COM],
--        [ddlEnvInterestStatus_ID],
--        [ddlEnvInterestStatus_VAL],
--        [ddlEnvInterestStatus_TAG],
--        [ddlEnvInterestStatus_VIS],
--        [ddlEnvInterestStatus_HIS],
--        [ddlEnvInterestStatus_DES],
--        [ddlEnvInterestStatus_COM],
--        [ddlOwnershipType_ID],
--        [ddlOwnershipType_VAL],
--        [ddlOwnershipType_TAG],
--        [ddlOwnershipType_VIS],
--        [ddlOwnershipType_HIS],
--        [ddlOwnershipType_DES],
--        [ddlOwnershipType_COM],
--        [txtComment_ID],
--        [txtComment_VAL],
--        [txtComment_TAG],
--        [txtComment_VIS],
--        [txtComment_HIS],
--        [txtComment_DES],
--        [txtComment_COM],
--        [txtPermittedCapacity_ID],
--        [txtPermittedCapacity_VAL],
--        [txtPermittedCapacity_TAG],
--        [txtPermittedCapacity_VIS],
--        [txtPermittedCapacity_HIS],
--        [txtPermittedCapacity_DES],
--        [txtPermittedCapacity_COM],
--        [txtTotalAcreage_ID],
--        [txtTotalAcreage_VAL],
--        [txtTotalAcreage_TAG],
--        [txtTotalAcreage_VIS],
--        [txtTotalAcreage_HIS],
--        [txtTotalAcreage_DES],
--        [txtTotalAcreage_COM],
--        [rdoGWInstalled_ID],
--        [rdoGWInstalled_VAL],
--        [rdoGWInstalled_TAG],
--        [rdoGWInstalled_VIS],
--        [rdoGWInstalled_HIS],
--        [rdoGWInstalled_DES],
--        [rdoGWInstalled_COM],
--        [ddlAssessmentMonitoring_ID],
--        [ddlAssessmentMonitoring_VAL],
--        [ddlAssessmentMonitoring_TAG],
--        [ddlAssessmentMonitoring_VIS],
--        [ddlAssessmentMonitoring_HIS],
--        [ddlAssessmentMonitoring_DES],
--        [ddlAssessmentMonitoring_COM],
--        [rdoMethaneInstalled_ID],
--        [rdoMethaneInstalled_VAL],
--        [rdoMethaneInstalled_TAG],
--        [rdoMethaneInstalled_VIS],
--        [rdoMethaneInstalled_HIS],
--        [rdoMethaneInstalled_DES],
--        [rdoMethaneInstalled_COM],
--        [ddlMethaneMonitoringFrequency_ID],
--        [ddlMethaneMonitoringFrequency_VAL],
--        [ddlMethaneMonitoringFrequency_TAG],
--        [ddlMethaneMonitoringFrequency_VIS],
--        [ddlMethaneMonitoringFrequency_HIS],
--        [ddlMethaneMonitoringFrequency_DES],
--        [ddlMethaneMonitoringFrequency_COM],
--        [rdoUnderDrainInstalled_ID],
--        [rdoUnderDrainInstalled_VAL],
--        [rdoUnderDrainInstalled_TAG],
--        [rdoUnderDrainInstalled_VIS],
--        [rdoUnderDrainInstalled_HIS],
--        [rdoUnderDrainInstalled_DES],
--        [rdoUnderDrainInstalled_COM],
--        [rdoLFGasInstalled_ID],
--        [rdoLFGasInstalled_VAL],
--        [rdoLFGasInstalled_TAG],
--        [rdoLFGasInstalled_VIS],
--        [rdoLFGasInstalled_HIS],
--        [rdoLFGasInstalled_DES],
--        [rdoLFGasInstalled_COM],
--        [rdoWasteEnergyOnsite_ID],
--        [rdoWasteEnergyOnsite_VAL],
--        [rdoWasteEnergyOnsite_TAG],
--        [rdoWasteEnergyOnsite_VIS],
--        [rdoWasteEnergyOnsite_HIS],
--        [rdoWasteEnergyOnsite_DES],
--        [rdoWasteEnergyOnsite_COM],
--        [txtEnergyProduced_ID],
--        [txtEnergyProduced_VAL],
--        [txtEnergyProduced_TAG],
--        [txtEnergyProduced_VIS],
--        [txtEnergyProduced_HIS],
--        [txtEnergyProduced_DES],
--        [txtEnergyProduced_COM],
--        [txtPermitIssueDate_ID],
--        [txtPermitIssueDate_VAL],
--        [txtPermitIssueDate_TAG],
--        [txtPermitIssueDate_VIS],
--        [txtPermitIssueDate_HIS],
--        [txtPermitIssueDate_DES],
--        [txtPermitIssueDate_COM],
--        [txtPermitReviewDueDate_ID],
--        [txtPermitReviewDueDate_VAL],
--        [txtPermitReviewDueDate_TAG],
--        [txtPermitReviewDueDate_VIS],
--        [txtPermitReviewDueDate_HIS],
--        [txtPermitReviewDueDate_DES],
--        [txtPermitReviewDueDate_COM],
--        [txtWasteTypesAccepted_ID],
--        [txtWasteTypesAccepted_VAL],
--        [txtWasteTypesAccepted_TAG],
--        [txtWasteTypesAccepted_VIS],
--        [txtWasteTypesAccepted_HIS],
--        [txtWasteTypesAccepted_DES],
--        [txtWasteTypesAccepted_COM],
--        [txtMaterialsNotAccepted_ID],
--        [txtMaterialsNotAccepted_VAL],
--        [txtMaterialsNotAccepted_TAG],
--        [txtMaterialsNotAccepted_VIS],
--        [txtMaterialsNotAccepted_HIS],
--        [txtMaterialsNotAccepted_DES],
--        [txtMaterialsNotAccepted_COM],
--        [txtMaterialsRecovered_ID],
--        [txtMaterialsRecovered_VAL],
--        [txtMaterialsRecovered_TAG],
--        [txtMaterialsRecovered_VIS],
--        [txtMaterialsRecovered_HIS],
--        [txtMaterialsRecovered_DES],
--        [txtMaterialsRecovered_COM],
--        [txtStorageCapacity_ID],
--        [txtStorageCapacity_VAL],
--        [txtStorageCapacity_TAG],
--        [txtStorageCapacity_VIS],
--        [txtStorageCapacity_HIS],
--        [txtStorageCapacity_DES],
--        [txtStorageCapacity_COM],
--        [txtStorageDuration_ID],
--        [txtStorageDuration_VAL],
--        [txtStorageDuration_TAG],
--        [txtStorageDuration_VIS],
--        [txtStorageDuration_HIS],
--        [txtStorageDuration_DES],
--        [txtStorageDuration_COM],
--        [rdoAcceptPublicWaste_ID],
--        [rdoAcceptPublicWaste_VAL],
--        [rdoAcceptPublicWaste_TAG],
--        [rdoAcceptPublicWaste_VIS],
--        [rdoAcceptPublicWaste_HIS],
--        [rdoAcceptPublicWaste_DES],
--        [rdoAcceptPublicWaste_COM],
--        [grdClosure],
--        [grdConstructionDetail],
--        [grdMajorModification],
--        [grdFinancialAssurance],
--        [FACILITY_ID_REF])
SELECT [PermitNumber],
       [EnvIntType],
       [txtPermitNumber_ID],
       [txtPermitNumber_VAL],
       [txtPermitNumber_TAG],
       [txtPermitNumber_VIS],
       [txtPermitNumber_HIS],
       [txtPermitNumber_DES],
       [txtPermitNumber_COM],
       [ddlEnvInterestStatus_ID],
       [ddlEnvInterestStatus_VAL],
       [ddlEnvInterestStatus_TAG],
       [ddlEnvInterestStatus_VIS],
       [ddlEnvInterestStatus_HIS],
       [ddlEnvInterestStatus_DES],
       [ddlEnvInterestStatus_COM],
       [ddlOwnershipType_ID],
       [ddlOwnershipType_VAL],
       [ddlOwnershipType_TAG],
       [ddlOwnershipType_VIS],
       [ddlOwnershipType_HIS],
       [ddlOwnershipType_DES],
       [ddlOwnershipType_COM],
       [txtComment_ID],
       [txtComment_VAL],
       [txtComment_TAG],
       [txtComment_VIS],
       [txtComment_HIS],
       [txtComment_DES],
       [txtComment_COM],
       [txtPermittedCapacity_ID],
       [txtPermittedCapacity_VAL],
       [txtPermittedCapacity_TAG],
       [txtPermittedCapacity_VIS],
       [txtPermittedCapacity_HIS],
       [txtPermittedCapacity_DES],
       [txtPermittedCapacity_COM],
       [txtTotalAcreage_ID],
       [txtTotalAcreage_VAL],
       [txtTotalAcreage_TAG],
       [txtTotalAcreage_VIS],
       [txtTotalAcreage_HIS],
       [txtTotalAcreage_DES],
       [txtTotalAcreage_COM],
       [rdoGWInstalled_ID],
       [rdoGWInstalled_VAL],
       [rdoGWInstalled_TAG],
       [rdoGWInstalled_VIS],
       [rdoGWInstalled_HIS],
       [rdoGWInstalled_DES],
       [rdoGWInstalled_COM],
       [ddlAssessmentMonitoring_ID],
       [ddlAssessmentMonitoring_VAL],
       [ddlAssessmentMonitoring_TAG],
       [ddlAssessmentMonitoring_VIS],
       [ddlAssessmentMonitoring_HIS],
       [ddlAssessmentMonitoring_DES],
       [ddlAssessmentMonitoring_COM],
       [rdoMethaneInstalled_ID],
       [rdoMethaneInstalled_VAL],
       [rdoMethaneInstalled_TAG],
       [rdoMethaneInstalled_VIS],
       [rdoMethaneInstalled_HIS],
       [rdoMethaneInstalled_DES],
       [rdoMethaneInstalled_COM],
       [ddlMethaneMonitoringFrequency_ID],
       [ddlMethaneMonitoringFrequency_VAL],
       [ddlMethaneMonitoringFrequency_TAG],
       [ddlMethaneMonitoringFrequency_VIS],
       [ddlMethaneMonitoringFrequency_HIS],
       [ddlMethaneMonitoringFrequency_DES],
       [ddlMethaneMonitoringFrequency_COM],
       [rdoUnderDrainInstalled_ID],
       [rdoUnderDrainInstalled_VAL],
       [rdoUnderDrainInstalled_TAG],
       [rdoUnderDrainInstalled_VIS],
       [rdoUnderDrainInstalled_HIS],
       [rdoUnderDrainInstalled_DES],
       [rdoUnderDrainInstalled_COM],
       [rdoLFGasInstalled_ID],
       [rdoLFGasInstalled_VAL],
       [rdoLFGasInstalled_TAG],
       [rdoLFGasInstalled_VIS],
       [rdoLFGasInstalled_HIS],
       [rdoLFGasInstalled_DES],
       [rdoLFGasInstalled_COM],
       [rdoWasteEnergyOnsite_ID],
       [rdoWasteEnergyOnsite_VAL],
       [rdoWasteEnergyOnsite_TAG],
       [rdoWasteEnergyOnsite_VIS],
       [rdoWasteEnergyOnsite_HIS],
       [rdoWasteEnergyOnsite_DES],
       [rdoWasteEnergyOnsite_COM],
       [txtEnergyProduced_ID],
       [txtEnergyProduced_VAL],
       [txtEnergyProduced_TAG],
       [txtEnergyProduced_VIS],
       [txtEnergyProduced_HIS],
       [txtEnergyProduced_DES],
       [txtEnergyProduced_COM],
       [txtPermitIssueDate_ID],
       [txtPermitIssueDate_VAL],
       [txtPermitIssueDate_TAG],
       [txtPermitIssueDate_VIS],
       [txtPermitIssueDate_HIS],
       [txtPermitIssueDate_DES],
       [txtPermitIssueDate_COM],
       [txtPermitReviewDueDate_ID],
       [txtPermitReviewDueDate_VAL],
       [txtPermitReviewDueDate_TAG],
       [txtPermitReviewDueDate_VIS],
       [txtPermitReviewDueDate_HIS],
       [txtPermitReviewDueDate_DES],
       [txtPermitReviewDueDate_COM],
       [txtWasteTypesAccepted_ID],
       [txtWasteTypesAccepted_VAL],
       [txtWasteTypesAccepted_TAG],
       [txtWasteTypesAccepted_VIS],
       [txtWasteTypesAccepted_HIS],
       [txtWasteTypesAccepted_DES],
       [txtWasteTypesAccepted_COM],
       [txtMaterialsNotAccepted_ID],
       [txtMaterialsNotAccepted_VAL],
       [txtMaterialsNotAccepted_TAG],
       [txtMaterialsNotAccepted_VIS],
       [txtMaterialsNotAccepted_HIS],
       [txtMaterialsNotAccepted_DES],
       [txtMaterialsNotAccepted_COM],
       [txtMaterialsRecovered_ID],
       [txtMaterialsRecovered_VAL],
       [txtMaterialsRecovered_TAG],
       [txtMaterialsRecovered_VIS],
       [txtMaterialsRecovered_HIS],
       [txtMaterialsRecovered_DES],
       [txtMaterialsRecovered_COM],
       [txtStorageCapacity_ID],
       [txtStorageCapacity_VAL],
       [txtStorageCapacity_TAG],
       [txtStorageCapacity_VIS],
       [txtStorageCapacity_HIS],
       [txtStorageCapacity_DES],
       [txtStorageCapacity_COM],
       [txtStorageDuration_ID],
       [txtStorageDuration_VAL],
       [txtStorageDuration_TAG],
       [txtStorageDuration_VIS],
       [txtStorageDuration_HIS],
       [txtStorageDuration_DES],
       [txtStorageDuration_COM],
       [rdoAcceptPublicWaste_ID],
       [rdoAcceptPublicWaste_VAL],
       [rdoAcceptPublicWaste_TAG],
       [rdoAcceptPublicWaste_VIS],
       [rdoAcceptPublicWaste_HIS],
       [rdoAcceptPublicWaste_DES],
       [rdoAcceptPublicWaste_COM],
       [grdClosure],
       [grdConstructionDetail],
       [grdMajorModification],
       [grdFinancialAssurance],
       [FACILITY_ID_REF]
FROM [dbo].[EI_MRF]  -- insert correct DB name and values
GO


