
/*****************************************************
*** Insert into LEMIR_Stage values for EI "CO" XML ***
*****************************************************/

--
USE [LEMIR_Stage]
GO
--
--INSERT INTO [dbo].[EI_CO]
--       ([PermitNumber],
--        [EnvIntType],
--        [txtPermitNumber_ID],
--        [txtPermitNumber_VAL],
--        [txtPermitNumber_TAG],
--        [txtPermitNumber_VIS],
--        [txtPermitNumber_HIS],
--        [txtPermitNumber_DES],
--        [txtPermitNumber_COM],
--        [ddlEnvInterestStatus_ID],
--        [ddlEnvInterestStatus_VAL],
--        [ddlEnvInterestStatus_TAG],
--        [ddlEnvInterestStatus_VIS],
--        [ddlEnvInterestStatus_HIS],
--        [ddlEnvInterestStatus_DES],
--        [ddlEnvInterestStatus_COM],
--        [ddlOwnershipType_ID],
--        [ddlOwnershipType_VAL],
--        [ddlOwnershipType_TAG],
--        [ddlOwnershipType_VIS],
--        [ddlOwnershipType_HIS],
--        [ddlOwnershipType_DES],
--        [ddlOwnershipType_COM],
--        [txtComment_ID],
--        [txtComment_VAL],
--        [txtComment_TAG],
--        [txtComment_VIS],
--        [txtComment_HIS],
--        [txtComment_DES],
--        [txtComment_COM],
--        [rdoGWInstalled_ID],
--        [rdoGWInstalled_VAL],
--        [rdoGWInstalled_TAG],
--        [rdoGWInstalled_VIS],
--        [rdoGWInstalled_HIS],
--        [rdoGWInstalled_DES],
--        [rdoGWInstalled_COM],
--        [ddlAssessmentMonitoring_ID],
--        [ddlAssessmentMonitoring_VAL],
--        [ddlAssessmentMonitoring_TAG],
--        [ddlAssessmentMonitoring_VIS],
--        [ddlAssessmentMonitoring_HIS],
--        [ddlAssessmentMonitoring_DES],
--        [ddlAssessmentMonitoring_COM],
--        [rdoMethaneInstalled_ID],
--        [rdoMethaneInstalled_VAL],
--        [rdoMethaneInstalled_TAG],
--        [rdoMethaneInstalled_VIS],
--        [rdoMethaneInstalled_HIS],
--        [rdoMethaneInstalled_DES],
--        [rdoMethaneInstalled_COM],
--        [ddlMethaneMonitoringFrequency_ID],
--        [ddlMethaneMonitoringFrequency_VAL],
--        [ddlMethaneMonitoringFrequency_TAG],
--        [ddlMethaneMonitoringFrequency_VIS],
--        [ddlMethaneMonitoringFrequency_HIS],
--        [ddlMethaneMonitoringFrequency_DES],
--        [ddlMethaneMonitoringFrequency_COM],
--        [rdoUnderDrainInstalled_ID],
--        [rdoUnderDrainInstalled_VAL],
--        [rdoUnderDrainInstalled_TAG],
--        [rdoUnderDrainInstalled_VIS],
--        [rdoUnderDrainInstalled_HIS],
--        [rdoUnderDrainInstalled_DES],
--        [rdoUnderDrainInstalled_COM],
--        [rdoLFGasInstalled_ID],
--        [rdoLFGasInstalled_VAL],
--        [rdoLFGasInstalled_TAG],
--        [rdoLFGasInstalled_VIS],
--        [rdoLFGasInstalled_HIS],
--        [rdoLFGasInstalled_DES],
--        [rdoLFGasInstalled_COM],
--        [rdoWasteEnergyOnsite_ID],
--        [rdoWasteEnergyOnsite_VAL],
--        [rdoWasteEnergyOnsite_TAG],
--        [rdoWasteEnergyOnsite_VIS],
--        [rdoWasteEnergyOnsite_HIS],
--        [rdoWasteEnergyOnsite_DES],
--        [rdoWasteEnergyOnsite_COM],
--        [txtEnergyProduced_ID],
--        [txtEnergyProduced_VAL],
--        [txtEnergyProduced_TAG],
--        [txtEnergyProduced_VIS],
--        [txtEnergyProduced_HIS],
--        [txtEnergyProduced_DES],
--        [txtEnergyProduced_COM],
--        [txtPermitIssueDate_ID],
--        [txtPermitIssueDate_VAL],
--        [txtPermitIssueDate_TAG],
--        [txtPermitIssueDate_VIS],
--        [txtPermitIssueDate_HIS],
--        [txtPermitIssueDate_DES],
--        [txtPermitIssueDate_COM],
--        [txtPermitReviewDueDate_ID],
--        [txtPermitReviewDueDate_VAL],
--        [txtPermitReviewDueDate_TAG],
--        [txtPermitReviewDueDate_VIS],
--        [txtPermitReviewDueDate_HIS],
--        [txtPermitReviewDueDate_DES],
--        [txtPermitReviewDueDate_COM],
--        [txtPermittedCapacity_ID],
--        [txtPermittedCapacity_VAL],
--        [txtPermittedCapacity_TAG],
--        [txtPermittedCapacity_VIS],
--        [txtPermittedCapacity_HIS],
--        [txtPermittedCapacity_DES],
--        [txtPermittedCapacity_COM],
--        [txtTotalAcreage_ID],
--        [txtTotalAcreage_VAL],
--        [txtTotalAcreage_TAG],
--        [txtTotalAcreage_VIS],
--        [txtTotalAcreage_HIS],
--        [txtTotalAcreage_DES],
--        [txtTotalAcreage_COM],
--        [chkCompostingClass_ID],
--        [chkCompostingClass_VAL],
--        [chkCompostingClass_TAG],
--        [chkCompostingClass_VIS],
--        [chkCompostingClass_HIS],
--        [chkCompostingClass_DES],
--        [chkCompostingClass_COM],
--        [chkFeedstockCategories_ID],
--        [chkFeedstockCategories_VAL],
--        [chkFeedstockCategories_TAG],
--        [chkFeedstockCategories_VIS],
--        [chkFeedstockCategories_HIS],
--        [chkFeedstockCategories_DES],
--        [chkFeedstockCategories_COM],
--        [txtFeedstockTypes_ID],
--        [txtFeedstockTypes_VAL],
--        [txtFeedstockTypes_TAG],
--        [txtFeedstockTypes_VIS],
--        [txtFeedstockTypes_HIS],
--        [txtFeedstockTypes_DES],
--        [txtFeedstockTypes_COM],
--        [txtCompostingMethod_ID],
--        [txtCompostingMethod_VAL],
--        [txtCompostingMethod_TAG],
--        [txtCompostingMethod_VIS],
--        [txtCompostingMethod_HIS],
--        [txtCompostingMethod_DES],
--        [txtCompostingMethod_COM],
--        [txtCompostingPadType_ID],
--        [txtCompostingPadType_VAL],
--        [txtCompostingPadType_TAG],
--        [txtCompostingPadType_VIS],
--        [txtCompostingPadType_HIS],
--        [txtCompostingPadType_DES],
--        [txtCompostingPadType_COM],
--        [txtActiveCompostingArea_ID],
--        [txtActiveCompostingArea_VAL],
--        [txtActiveCompostingArea_TAG],
--        [txtActiveCompostingArea_VIS],
--        [txtActiveCompostingArea_HIS],
--        [txtActiveCompostingArea_DES],
--        [txtActiveCompostingArea_COM],
--        [rdoAcceptPublicWaste_ID],
--        [rdoAcceptPublicWaste_VAL],
--        [rdoAcceptPublicWaste_TAG],
--        [rdoAcceptPublicWaste_VIS],
--        [rdoAcceptPublicWaste_HIS],
--        [rdoAcceptPublicWaste_DES],
--        [rdoAcceptPublicWaste_COM],
--        [grdClosure],
--        [grdConstructionDetail],
--        [grdMajorModification],
--        [grdFinancialAssurance],
--        [FACILITY_ID_REF])
SELECT [PermitNumber],
       [EnvIntType],
       [txtPermitNumber_ID],
       [txtPermitNumber_VAL],
       [txtPermitNumber_TAG],
       [txtPermitNumber_VIS],
       [txtPermitNumber_HIS],
       [txtPermitNumber_DES],
       [txtPermitNumber_COM],
       [ddlEnvInterestStatus_ID],
       [ddlEnvInterestStatus_VAL],
       [ddlEnvInterestStatus_TAG],
       [ddlEnvInterestStatus_VIS],
       [ddlEnvInterestStatus_HIS],
       [ddlEnvInterestStatus_DES],
       [ddlEnvInterestStatus_COM],
       [ddlOwnershipType_ID],
       [ddlOwnershipType_VAL],
       [ddlOwnershipType_TAG],
       [ddlOwnershipType_VIS],
       [ddlOwnershipType_HIS],
       [ddlOwnershipType_DES],
       [ddlOwnershipType_COM],
       [txtComment_ID],
       [txtComment_VAL],
       [txtComment_TAG],
       [txtComment_VIS],
       [txtComment_HIS],
       [txtComment_DES],
       [txtComment_COM],
       [rdoGWInstalled_ID],
       [rdoGWInstalled_VAL],
       [rdoGWInstalled_TAG],
       [rdoGWInstalled_VIS],
       [rdoGWInstalled_HIS],
       [rdoGWInstalled_DES],
       [rdoGWInstalled_COM],
       [ddlAssessmentMonitoring_ID],
       [ddlAssessmentMonitoring_VAL],
       [ddlAssessmentMonitoring_TAG],
       [ddlAssessmentMonitoring_VIS],
       [ddlAssessmentMonitoring_HIS],
       [ddlAssessmentMonitoring_DES],
       [ddlAssessmentMonitoring_COM],
       [rdoMethaneInstalled_ID],
       [rdoMethaneInstalled_VAL],
       [rdoMethaneInstalled_TAG],
       [rdoMethaneInstalled_VIS],
       [rdoMethaneInstalled_HIS],
       [rdoMethaneInstalled_DES],
       [rdoMethaneInstalled_COM],
       [ddlMethaneMonitoringFrequency_ID],
       [ddlMethaneMonitoringFrequency_VAL],
       [ddlMethaneMonitoringFrequency_TAG],
       [ddlMethaneMonitoringFrequency_VIS],
       [ddlMethaneMonitoringFrequency_HIS],
       [ddlMethaneMonitoringFrequency_DES],
       [ddlMethaneMonitoringFrequency_COM],
       [rdoUnderDrainInstalled_ID],
       [rdoUnderDrainInstalled_VAL],
       [rdoUnderDrainInstalled_TAG],
       [rdoUnderDrainInstalled_VIS],
       [rdoUnderDrainInstalled_HIS],
       [rdoUnderDrainInstalled_DES],
       [rdoUnderDrainInstalled_COM],
       [rdoLFGasInstalled_ID],
       [rdoLFGasInstalled_VAL],
       [rdoLFGasInstalled_TAG],
       [rdoLFGasInstalled_VIS],
       [rdoLFGasInstalled_HIS],
       [rdoLFGasInstalled_DES],
       [rdoLFGasInstalled_COM],
       [rdoWasteEnergyOnsite_ID],
       [rdoWasteEnergyOnsite_VAL],
       [rdoWasteEnergyOnsite_TAG],
       [rdoWasteEnergyOnsite_VIS],
       [rdoWasteEnergyOnsite_HIS],
       [rdoWasteEnergyOnsite_DES],
       [rdoWasteEnergyOnsite_COM],
       [txtEnergyProduced_ID],
       [txtEnergyProduced_VAL],
       [txtEnergyProduced_TAG],
       [txtEnergyProduced_VIS],
       [txtEnergyProduced_HIS],
       [txtEnergyProduced_DES],
       [txtEnergyProduced_COM],
       [txtPermitIssueDate_ID],
       [txtPermitIssueDate_VAL],
       [txtPermitIssueDate_TAG],
       [txtPermitIssueDate_VIS],
       [txtPermitIssueDate_HIS],
       [txtPermitIssueDate_DES],
       [txtPermitIssueDate_COM],
       [txtPermitReviewDueDate_ID],
       [txtPermitReviewDueDate_VAL],
       [txtPermitReviewDueDate_TAG],
       [txtPermitReviewDueDate_VIS],
       [txtPermitReviewDueDate_HIS],
       [txtPermitReviewDueDate_DES],
       [txtPermitReviewDueDate_COM],
       [txtPermittedCapacity_ID],
       [txtPermittedCapacity_VAL],
       [txtPermittedCapacity_TAG],
       [txtPermittedCapacity_VIS],
       [txtPermittedCapacity_HIS],
       [txtPermittedCapacity_DES],
       [txtPermittedCapacity_COM],
       [txtTotalAcreage_ID],
       [txtTotalAcreage_VAL],
       [txtTotalAcreage_TAG],
       [txtTotalAcreage_VIS],
       [txtTotalAcreage_HIS],
       [txtTotalAcreage_DES],
       [txtTotalAcreage_COM],
       [chkCompostingClass_ID],
       [chkCompostingClass_VAL],
       [chkCompostingClass_TAG],
       [chkCompostingClass_VIS],
       [chkCompostingClass_HIS],
       [chkCompostingClass_DES],
       [chkCompostingClass_COM],
       [chkFeedstockCategories_ID],
       [chkFeedstockCategories_VAL],
       [chkFeedstockCategories_TAG],
       [chkFeedstockCategories_VIS],
       [chkFeedstockCategories_HIS],
       [chkFeedstockCategories_DES],
       [chkFeedstockCategories_COM],
       [txtFeedstockTypes_ID],
       [txtFeedstockTypes_VAL],
       [txtFeedstockTypes_TAG],
       [txtFeedstockTypes_VIS],
       [txtFeedstockTypes_HIS],
       [txtFeedstockTypes_DES],
       [txtFeedstockTypes_COM],
       [txtCompostingMethod_ID],
       [txtCompostingMethod_VAL],
       [txtCompostingMethod_TAG],
       [txtCompostingMethod_VIS],
       [txtCompostingMethod_HIS],
       [txtCompostingMethod_DES],
       [txtCompostingMethod_COM],
       [txtCompostingPadType_ID],
       [txtCompostingPadType_VAL],
       [txtCompostingPadType_TAG],
       [txtCompostingPadType_VIS],
       [txtCompostingPadType_HIS],
       [txtCompostingPadType_DES],
       [txtCompostingPadType_COM],
       [txtActiveCompostingArea_ID],
       [txtActiveCompostingArea_VAL],
       [txtActiveCompostingArea_TAG],
       [txtActiveCompostingArea_VIS],
       [txtActiveCompostingArea_HIS],
       [txtActiveCompostingArea_DES],
       [txtActiveCompostingArea_COM],
       [rdoAcceptPublicWaste_ID],
       [rdoAcceptPublicWaste_VAL],
       [rdoAcceptPublicWaste_TAG],
       [rdoAcceptPublicWaste_VIS],
       [rdoAcceptPublicWaste_HIS],
       [rdoAcceptPublicWaste_DES],
       [rdoAcceptPublicWaste_COM],
       [grdClosure],
       [grdConstructionDetail],
       [grdMajorModification],
       [grdFinancialAssurance],
       [FACILITY_ID_REF]
FROM [dbo].[EI_CO]  -- insert correct DB name and values
GO


