
/******************************************************
*** Insert into LEMIR_Stage values for EI "COL" XML ***
******************************************************/

--
USE [LEMIR_Stage]
GO
--
--INSERT INTO [dbo].[EI_COL]
--       ([PermitNumber],
--        [EnvIntType],
--        [txtPermitNumber_ID],
--        [txtPermitNumber_VAL],
--        [txtPermitNumber_TAG],
--        [txtPermitNumber_VIS],
--        [txtPermitNumber_HIS],
--        [txtPermitNumber_DES],
--        [txtPermitNumber_COM],
--        [ddlEnvInterestStatus_ID],
--        [ddlEnvInterestStatus_VAL],
--        [ddlEnvInterestStatus_TAG],
--        [ddlEnvInterestStatus_VIS],
--        [ddlEnvInterestStatus_HIS],
--        [ddlEnvInterestStatus_DES],
--        [ddlEnvInterestStatus_COM],
--        [ddlOwnershipType_ID],
--        [ddlOwnershipType_VAL],
--        [ddlOwnershipType_TAG],
--        [ddlOwnershipType_VIS],
--        [ddlOwnershipType_HIS],
--        [ddlOwnershipType_DES],
--        [ddlOwnershipType_COM],
--        [txtComment_ID],
--        [txtComment_VAL],
--        [txtComment_TAG],
--        [txtComment_VIS],
--        [txtComment_HIS],
--        [txtComment_DES],
--        [txtComment_COM],
--        [txtFacilityStartDate_ID],
--        [txtFacilityStartDate_VAL],
--        [txtFacilityStartDate_TAG],
--        [txtFacilityStartDate_VIS],
--        [txtFacilityStartDate_HIS],
--        [txtFacilityStartDate_DES],
--        [txtFacilityStartDate_COM],
--        [txtFacilityEndDate_ID],
--        [txtFacilityEndDate_VAL],
--        [txtFacilityEndDate_TAG],
--        [txtFacilityEndDate_VIS],
--        [txtFacilityEndDate_HIS],
--        [txtFacilityEndDate_DES],
--        [txtFacilityEndDate_COM],
--        [txtPBRApprovalDate_ID],
--        [txtPBRApprovalDate_VAL],
--        [txtPBRApprovalDate_TAG],
--        [txtPBRApprovalDate_VIS],
--        [txtPBRApprovalDate_HIS],
--        [txtPBRApprovalDate_DES],
--        [txtPBRApprovalDate_COM],
--        [txtClosureAcknowledgedDate_ID],
--        [txtClosureAcknowledgedDate_VAL],
--        [txtClosureAcknowledgedDate_TAG],
--        [txtClosureAcknowledgedDate_VIS],
--        [txtClosureAcknowledgedDate_HIS],
--        [txtClosureAcknowledgedDate_DES],
--        [txtClosureAcknowledgedDate_COM],
--        [txtSolidWasteHandled_ID],
--        [txtSolidWasteHandled_VAL],
--        [txtSolidWasteHandled_TAG],
--        [txtSolidWasteHandled_VIS],
--        [txtSolidWasteHandled_HIS],
--        [txtSolidWasteHandled_DES],
--        [txtSolidWasteHandled_COM],
--        [rdoAcceptPublicWaste_ID],
--        [rdoAcceptPublicWaste_VAL],
--        [rdoAcceptPublicWaste_TAG],
--        [rdoAcceptPublicWaste_VIS],
--        [rdoAcceptPublicWaste_HIS],
--        [rdoAcceptPublicWaste_DES],
--        [rdoAcceptPublicWaste_COM],
--        [FACILITY_ID_REF])
SELECT [PermitNumber],
       [EnvIntType],
       [txtPermitNumber_ID],
       [txtPermitNumber_VAL],
       [txtPermitNumber_TAG],
       [txtPermitNumber_VIS],
       [txtPermitNumber_HIS],
       [txtPermitNumber_DES],
       [txtPermitNumber_COM],
       [ddlEnvInterestStatus_ID],
       [ddlEnvInterestStatus_VAL],
       [ddlEnvInterestStatus_TAG],
       [ddlEnvInterestStatus_VIS],
       [ddlEnvInterestStatus_HIS],
       [ddlEnvInterestStatus_DES],
       [ddlEnvInterestStatus_COM],
       [ddlOwnershipType_ID],
       [ddlOwnershipType_VAL],
       [ddlOwnershipType_TAG],
       [ddlOwnershipType_VIS],
       [ddlOwnershipType_HIS],
       [ddlOwnershipType_DES],
       [ddlOwnershipType_COM],
       [txtComment_ID],
       [txtComment_VAL],
       [txtComment_TAG],
       [txtComment_VIS],
       [txtComment_HIS],
       [txtComment_DES],
       [txtComment_COM],
       [txtFacilityStartDate_ID],
       [txtFacilityStartDate_VAL],
       [txtFacilityStartDate_TAG],
       [txtFacilityStartDate_VIS],
       [txtFacilityStartDate_HIS],
       [txtFacilityStartDate_DES],
       [txtFacilityStartDate_COM],
       [txtFacilityEndDate_ID],
       [txtFacilityEndDate_VAL],
       [txtFacilityEndDate_TAG],
       [txtFacilityEndDate_VIS],
       [txtFacilityEndDate_HIS],
       [txtFacilityEndDate_DES],
       [txtFacilityEndDate_COM],
       [txtPBRApprovalDate_ID],
       [txtPBRApprovalDate_VAL],
       [txtPBRApprovalDate_TAG],
       [txtPBRApprovalDate_VIS],
       [txtPBRApprovalDate_HIS],
       [txtPBRApprovalDate_DES],
       [txtPBRApprovalDate_COM],
       [txtClosureAcknowledgedDate_ID],
       [txtClosureAcknowledgedDate_VAL],
       [txtClosureAcknowledgedDate_TAG],
       [txtClosureAcknowledgedDate_VIS],
       [txtClosureAcknowledgedDate_HIS],
       [txtClosureAcknowledgedDate_DES],
       [txtClosureAcknowledgedDate_COM],
       [txtSolidWasteHandled_ID],
       [txtSolidWasteHandled_VAL],
       [txtSolidWasteHandled_TAG],
       [txtSolidWasteHandled_VIS],
       [txtSolidWasteHandled_HIS],
       [txtSolidWasteHandled_DES],
       [txtSolidWasteHandled_COM],
       [rdoAcceptPublicWaste_ID],
       [rdoAcceptPublicWaste_VAL],
       [rdoAcceptPublicWaste_TAG],
       [rdoAcceptPublicWaste_VIS],
       [rdoAcceptPublicWaste_HIS],
       [rdoAcceptPublicWaste_DES],
       [rdoAcceptPublicWaste_COM],
       [FACILITY_ID_REF]
FROM [dbo].[EI_COL]  -- insert correct DB name and values
GO


