
/*******************************************************
*** Insert into LEMIR_Stage values for EI "CCRL" XML ***
*******************************************************/

--
USE [LEMIR_Stage]
GO
--
--INSERT INTO [dbo].[EI_CCRL]
--       ([PermitNumber],
--        [txtPermitNumber_ID],
--        [txtPermitNumber_VAL],
--        [txtPermitNumber_TAG],
--        [txtPermitNumber_VIS],
--        [txtPermitNumber_HIS],
--        [txtPermitNumber_DES],
--        [txtPermitNumber_COM],
--        [ddlEnvInterestStatus_ID],
--        [ddlEnvInterestStatus_VAL],
--        [ddlEnvInterestStatus_TAG],
--        [ddlEnvInterestStatus_VIS],
--        [ddlEnvInterestStatus_HIS],
--        [ddlEnvInterestStatus_DES],
--        [ddlEnvInterestStatus_COM],
--        [ddlOwnershipType_ID],
--        [ddlOwnershipType_VAL],
--        [ddlOwnershipType_TAG],
--        [ddlOwnershipType_VIS],
--        [ddlOwnershipType_HIS],
--        [ddlOwnershipType_DES],
--        [ddlOwnershipType_COM],
--        [txtWebsiteAddress_ID],
--        [txtWebsiteAddress_VAL],
--        [txtWebsiteAddress_TAG],
--        [txtWebsiteAddress_VIS],
--        [txtWebsiteAddress_HIS],
--        [txtWebsiteAddress_DES],
--        [txtWebsiteAddress_COM],
--        [txtComment_ID],
--        [txtComment_VAL],
--        [txtComment_TAG],
--        [txtComment_VIS],
--        [txtComment_HIS],
--        [txtComment_DES],
--        [txtComment_COM],
--        [txtPermittedCapacity_ID],
--        [txtPermittedCapacity_VAL],
--        [txtPermittedCapacity_TAG],
--        [txtPermittedCapacity_VIS],
--        [txtPermittedCapacity_HIS],
--        [txtPermittedCapacity_DES],
--        [txtPermittedCapacity_COM],
--        [txtRemainingCapacity_ID],
--        [txtRemainingCapacity_VAL],
--        [txtRemainingCapacity_TAG],
--        [txtRemainingCapacity_VIS],
--        [txtRemainingCapacity_HIS],
--        [txtRemainingCapacity_DES],
--        [txtRemainingCapacity_COM],
--        [txtRemainingLife_ID],
--        [txtRemainingLife_VAL],
--        [txtRemainingLife_TAG],
--        [txtRemainingLife_VIS],
--        [txtRemainingLife_HIS],
--        [txtRemainingLife_DES],
--        [txtRemainingLife_COM],
--        [txtTotalAcreage_ID],
--        [txtTotalAcreage_VAL],
--        [txtTotalAcreage_TAG],
--        [txtTotalAcreage_VIS],
--        [txtTotalAcreage_HIS],
--        [txtTotalAcreage_DES],
--        [txtTotalAcreage_COM],
--        [txtConstructedDisposalFootprint_ID],
--        [txtConstructedDisposalFootprint_VAL],
--        [txtConstructedDisposalFootprint_TAG],
--        [txtConstructedDisposalFootprint_VIS],
--        [txtConstructedDisposalFootprint_HIS],
--        [txtConstructedDisposalFootprint_DES],
--        [txtConstructedDisposalFootprint_COM],
--        [rdoGWInstalled_ID],
--        [rdoGWInstalled_VAL],
--        [rdoGWInstalled_TAG],
--        [rdoGWInstalled_VIS],
--        [rdoGWInstalled_HIS],
--        [rdoGWInstalled_DES],
--        [rdoGWInstalled_COM],
--        [ddlAssessmentMonitoring_ID],
--        [ddlAssessmentMonitoring_VAL],
--        [ddlAssessmentMonitoring_TAG],
--        [ddlAssessmentMonitoring_VIS],
--        [ddlAssessmentMonitoring_HIS],
--        [ddlAssessmentMonitoring_DES],
--        [ddlAssessmentMonitoring_COM],
--        [rdoMethaneInstalled_ID],
--        [rdoMethaneInstalled_VAL],
--        [rdoMethaneInstalled_TAG],
--        [rdoMethaneInstalled_VIS],
--        [rdoMethaneInstalled_HIS],
--        [rdoMethaneInstalled_DES],
--        [rdoMethaneInstalled_COM],
--        [ddlMethaneMonitoringFrequency_ID],
--        [ddlMethaneMonitoringFrequency_VAL],
--        [ddlMethaneMonitoringFrequency_TAG],
--        [ddlMethaneMonitoringFrequency_VIS],
--        [ddlMethaneMonitoringFrequency_HIS],
--        [ddlMethaneMonitoringFrequency_DES],
--        [ddlMethaneMonitoringFrequency_COM],
--        [rdoUnderDrainInstalled_ID],
--        [rdoUnderDrainInstalled_VAL],
--        [rdoUnderDrainInstalled_TAG],
--        [rdoUnderDrainInstalled_VIS],
--        [rdoUnderDrainInstalled_HIS],
--        [rdoUnderDrainInstalled_DES],
--        [rdoUnderDrainInstalled_COM],
--        [rdoLFGasInstalled_ID],
--        [rdoLFGasInstalled_VAL],
--        [rdoLFGasInstalled_TAG],
--        [rdoLFGasInstalled_VIS],
--        [rdoLFGasInstalled_HIS],
--        [rdoLFGasInstalled_DES],
--        [rdoLFGasInstalled_COM],
--        [rdoWasteEnergyOnsite_ID],
--        [rdoWasteEnergyOnsite_VAL],
--        [rdoWasteEnergyOnsite_TAG],
--        [rdoWasteEnergyOnsite_VIS],
--        [rdoWasteEnergyOnsite_HIS],
--        [rdoWasteEnergyOnsite_DES],
--        [rdoWasteEnergyOnsite_COM],
--        [txtEnergyProduced_ID],
--        [txtEnergyProduced_VAL],
--        [txtEnergyProduced_TAG],
--        [txtEnergyProduced_VIS],
--        [txtEnergyProduced_HIS],
--        [txtEnergyProduced_DES],
--        [txtEnergyProduced_COM],
--        [txtPermitIssueDate_ID],
--        [txtPermitIssueDate_VAL],
--        [txtPermitIssueDate_TAG],
--        [txtPermitIssueDate_VIS],
--        [txtPermitIssueDate_HIS],
--        [txtPermitIssueDate_DES],
--        [txtPermitIssueDate_COM],
--        [txtPermitReviewDueDate_ID],
--        [txtPermitReviewDueDate_VAL],
--        [txtPermitReviewDueDate_TAG],
--        [txtPermitReviewDueDate_VIS],
--        [txtPermitReviewDueDate_HIS],
--        [txtPermitReviewDueDate_DES],
--        [txtPermitReviewDueDate_COM],
--        [txtPostClosureCarePeriod_ID],
--        [txtPostClosureCarePeriod_VAL],
--        [txtPostClosureCarePeriod_TAG],
--        [txtPostClosureCarePeriod_VIS],
--        [txtPostClosureCarePeriod_HIS],
--        [txtPostClosureCarePeriod_DES],
--        [txtPostClosureCarePeriod_COM],
--        [txtPostClosureReleaseDate_ID],
--        [txtPostClosureReleaseDate_VAL],
--        [txtPostClosureReleaseDate_TAG],
--        [txtPostClosureReleaseDate_VIS],
--        [txtPostClosureReleaseDate_HIS],
--        [txtPostClosureReleaseDate_DES],
--        [txtPostClosureReleaseDate_COM],
--        [rdoAcceptPublicWaste_ID],
--        [rdoAcceptPublicWaste_VAL],
--        [rdoAcceptPublicWaste_TAG],
--        [rdoAcceptPublicWaste_VIS],
--        [rdoAcceptPublicWaste_HIS],
--        [rdoAcceptPublicWaste_DES],
--        [rdoAcceptPublicWaste_COM],
--        [rdoAcceptCCR_ID],
--        [rdoAcceptCCR_VAL],
--        [rdoAcceptCCR_TAG],
--        [rdoAcceptCCR_VIS],
--        [rdoAcceptCCR_HIS],
--        [rdoAcceptCCR_DES],
--        [rdoAcceptCCR_COM],
--        [rdoAcceptAsbestos_ID],
--        [rdoAcceptAsbestos_VAL],
--        [rdoAcceptAsbestos_TAG],
--        [rdoAcceptAsbestos_VIS],
--        [rdoAcceptAsbestos_HIS],
--        [rdoAcceptAsbestos_DES],
--        [rdoAcceptAsbestos_COM],
--        [grdFinancialAssurance],
--        [grdClosure],
--        [grdConstructionDetail],
--        [grdMajorModification],
--        [FACILITY_ID_REF])
SELECT [MFI].[MainPermitNumber] AS [PermitNumber],
--
       'txtPermitNumber' AS [txtPermitNumber_ID],
       [MFI].[MainPermitNumber] AS [txtPermitNumber_VAL],
       'Permit Number' AS [txtPermitNumber_TAG],
       'true' AS [txtPermitNumber_VIS],
       [MFI].[MainPermitNumber]+'|'+convert(VARCHAR(50), getdate(), 101)+' '+LTRIM(RIGHT(CONVERT(CHAR(20), GETDATE(), 22), 11))+'|'+'EPDMIG SW||' AS [txtPermitNumber_HIS],
       'Permit Number:' AS [txtPermitNumber_DES],
       '' AS [txtPermitNumber_COM],
--
       'ddlEnvInterestStatus' AS [ddlEnvInterestStatus_ID],
       [MFI].[OperationStatus] AS [ddlEnvInterestStatus_VAL],
       'EI Status' AS [ddlEnvInterestStatus_TAG],
       'true' AS [ddlEnvInterestStatus_VIS],
       [MFI].[OperationStatus]+'|'+convert(VARCHAR(50), getdate(), 101)+' '+LTRIM(RIGHT(CONVERT(CHAR(20), GETDATE(), 22), 11))+'|'+'EPDMIG SW||' AS [ddlEnvInterestStatus_HIS],
       'EI Status:' AS [ddlEnvInterestStatus_DES],
       '' AS [ddlEnvInterestStatus_COM],
       --
       'rdoOwnershipType' AS [ddlOwnershipType_ID],
       [MFI].[Dominion] AS [ddlOwnershipType_VAL],
       'Ownership Type' AS [ddlOwnershipType_TAG],
       'true' AS [ddlOwnershipType_VIS],
       [MFI].[Dominion]+'|'+convert(VARCHAR(50), getdate(), 101)+' '+LTRIM(RIGHT(CONVERT(CHAR(20), GETDATE(), 22), 11))+'|'+'EPDMIG SW||' AS [ddlOwnershipType_HIS],
       'Ownership Type:' AS [ddlOwnershipType_DES],
       '' AS [ddlOwnershipType_COM],
       --
       NULL AS [txtWebsiteAddress_ID],
       NULL AS [txtWebsiteAddress_VAL],
       NULL AS [txtWebsiteAddress_TAG],
       NULL AS [txtWebsiteAddress_VIS],
       NULL AS [txtWebsiteAddress_HIS],
       NULL AS [txtWebsiteAddress_DES],
       NULL AS [txtWebsiteAddress_COM],
       --
       'txtComment' AS [txtComment_ID],
       isnull([MFI].[Comments], '') AS [txtComment_VAL],
       'General Comments' AS [txtComment_TAG],
       'true' AS [txtComment_VIS],
       isnull([MFI].[Comments], '')+'|'+convert(VARCHAR(50), getdate(), 101)+' '+LTRIM(RIGHT(CONVERT(CHAR(20), GETDATE(), 22), 11))+'|'+'EPDMIG SW||' AS [txtComment_HIS],
       'General Comments:' AS [txtComment_DES],
       '' AS [txtComment_COM],
       --
       'txtPermittedCapacity' AS [txtPermittedCapacity_ID],
       isnull(str([MFI].[PermittedCapacity(CY)], 20, 2), '') AS [txtPermittedCapacity_VAL],
       'Permitted Capacity (CY)' AS [txtPermittedCapacity_TAG],
       'true' AS [txtPermittedCapacity_VIS],
       isnull(str([MFI].[PermittedCapacity(CY)], 20, 2), '')+'|'+convert(VARCHAR(50), getdate(), 101)+' '+LTRIM(RIGHT(CONVERT(CHAR(20), GETDATE(), 22), 11))+'|'+'EPDMIG SW||' AS [txtPermittedCapacity_HIS],
       'Permitted Capacity (CY):' AS [txtPermittedCapacity_DES],
       '' AS [txtPermittedCapacity_COM],
       --
       --[txtRemainingCapacity_ID],
       --[txtRemainingCapacity_VAL],
       --[txtRemainingCapacity_TAG],
       --[txtRemainingCapacity_VIS],
       --[txtRemainingCapacity_HIS],
       --[txtRemainingCapacity_DES],
       --[txtRemainingCapacity_COM],
       --[txtRemainingLife_ID],
       --[txtRemainingLife_VAL],
       --[txtRemainingLife_TAG],
       --[txtRemainingLife_VIS],
       --[txtRemainingLife_HIS],
       --[txtRemainingLife_DES],
       --[txtRemainingLife_COM],
       --[txtTotalAcreage_ID],
       --[txtTotalAcreage_VAL],
       --[txtTotalAcreage_TAG],
       --[txtTotalAcreage_VIS],
       --[txtTotalAcreage_HIS],
       --[txtTotalAcreage_DES],
       --[txtTotalAcreage_COM],
       NULL AS [txtConstructedDisposalFootprint_ID],
       NULL AS [txtConstructedDisposalFootprint_VAL],
       NULL AS [txtConstructedDisposalFootprint_TAG],
       NULL AS [txtConstructedDisposalFootprint_VIS],
       NULL AS [txtConstructedDisposalFootprint_HIS],
       NULL AS [txtConstructedDisposalFootprint_DES],
       NULL AS [txtConstructedDisposalFootprint_COM],
       --[rdoGWInstalled_ID],
       --[rdoGWInstalled_VAL],
       --[rdoGWInstalled_TAG],
       --[rdoGWInstalled_VIS],
       --[rdoGWInstalled_HIS],
       --[rdoGWInstalled_DES],
       --[rdoGWInstalled_COM],
       --[ddlAssessmentMonitoring_ID],
       --[ddlAssessmentMonitoring_VAL],
       --[ddlAssessmentMonitoring_TAG],
       --[ddlAssessmentMonitoring_VIS],
       --[ddlAssessmentMonitoring_HIS],
       --[ddlAssessmentMonitoring_DES],
       --[ddlAssessmentMonitoring_COM],
       --[rdoMethaneInstalled_ID],
       --[rdoMethaneInstalled_VAL],
       --[rdoMethaneInstalled_TAG],
       --[rdoMethaneInstalled_VIS],
       --[rdoMethaneInstalled_HIS],
       --[rdoMethaneInstalled_DES],
       --[rdoMethaneInstalled_COM],
       --[ddlMethaneMonitoringFrequency_ID],
       --[ddlMethaneMonitoringFrequency_VAL],
       --[ddlMethaneMonitoringFrequency_TAG],
       --[ddlMethaneMonitoringFrequency_VIS],
       --[ddlMethaneMonitoringFrequency_HIS],
       --[ddlMethaneMonitoringFrequency_DES],
       --[ddlMethaneMonitoringFrequency_COM],
       --[rdoUnderDrainInstalled_ID],
       --[rdoUnderDrainInstalled_VAL],
       --[rdoUnderDrainInstalled_TAG],
       --[rdoUnderDrainInstalled_VIS],
       --[rdoUnderDrainInstalled_HIS],
       --[rdoUnderDrainInstalled_DES],
       --[rdoUnderDrainInstalled_COM],
       --[rdoLFGasInstalled_ID],
       --[rdoLFGasInstalled_VAL],
       --[rdoLFGasInstalled_TAG],
       --[rdoLFGasInstalled_VIS],
       --[rdoLFGasInstalled_HIS],
       --[rdoLFGasInstalled_DES],
       --[rdoLFGasInstalled_COM],
       --[rdoWasteEnergyOnsite_ID],
       --[rdoWasteEnergyOnsite_VAL],
       --[rdoWasteEnergyOnsite_TAG],
       --[rdoWasteEnergyOnsite_VIS],
       --[rdoWasteEnergyOnsite_HIS],
       --[rdoWasteEnergyOnsite_DES],
       --[rdoWasteEnergyOnsite_COM],
       --[txtEnergyProduced_ID],
       --[txtEnergyProduced_VAL],
       --[txtEnergyProduced_TAG],
       --[txtEnergyProduced_VIS],
       --[txtEnergyProduced_HIS],
       --[txtEnergyProduced_DES],
       --[txtEnergyProduced_COM],
       --[txtPermitIssueDate_ID],
       --[txtPermitIssueDate_VAL],
       --[txtPermitIssueDate_TAG],
       --[txtPermitIssueDate_VIS],
       --[txtPermitIssueDate_HIS],
       --[txtPermitIssueDate_DES],
       --[txtPermitIssueDate_COM],
       --[txtPermitReviewDueDate_ID],
       --[txtPermitReviewDueDate_VAL],
       --[txtPermitReviewDueDate_TAG],
       --[txtPermitReviewDueDate_VIS],
       --[txtPermitReviewDueDate_HIS],
       --[txtPermitReviewDueDate_DES],
       --[txtPermitReviewDueDate_COM],
       --[txtPostClosureCarePeriod_ID],
       --[txtPostClosureCarePeriod_VAL],
       --[txtPostClosureCarePeriod_TAG],
       --[txtPostClosureCarePeriod_VIS],
       --[txtPostClosureCarePeriod_HIS],
       --[txtPostClosureCarePeriod_DES],
       --[txtPostClosureCarePeriod_COM],
       --[txtPostClosureReleaseDate_ID],
       --[txtPostClosureReleaseDate_VAL],
       --[txtPostClosureReleaseDate_TAG],
       --[txtPostClosureReleaseDate_VIS],
       --[txtPostClosureReleaseDate_HIS],
       --[txtPostClosureReleaseDate_DES],
       --[txtPostClosureReleaseDate_COM],
       --[rdoAcceptPublicWaste_ID],
       --[rdoAcceptPublicWaste_VAL],
       --[rdoAcceptPublicWaste_TAG],
       --[rdoAcceptPublicWaste_VIS],
       --[rdoAcceptPublicWaste_HIS],
       --[rdoAcceptPublicWaste_DES],
       --[rdoAcceptPublicWaste_COM],
       --[rdoAcceptCCR_ID],
       --[rdoAcceptCCR_VAL],
       --[rdoAcceptCCR_TAG],
       --[rdoAcceptCCR_VIS],
       --[rdoAcceptCCR_HIS],
       --[rdoAcceptCCR_DES],
       --[rdoAcceptCCR_COM],
       --[rdoAcceptAsbestos_ID],
       --[rdoAcceptAsbestos_VAL],
       --[rdoAcceptAsbestos_TAG],
       --[rdoAcceptAsbestos_VIS],
       --[rdoAcceptAsbestos_HIS],
       --[rdoAcceptAsbestos_DES],
       --[rdoAcceptAsbestos_COM],
       --
       isnull(
    (SELECT DISTINCT
            convert(VARCHAR(50), [F].[txtFiscalYearEndDate], 101) AS [txtFiscalYearEndDate],
            convert(VARCHAR(50), [F].[txtEffectiveStartDate], 101) AS [txtEffectiveStartDate],
            convert(VARCHAR(50), [F].[txtEffectiveEndDate], 101) AS [txtEffectiveEndDate],
            [F].[ddlFAType] AS [ddlFAType],
            [F].[txtMechanismNo] AS [txtMechanismNo],
            [F].[txtCurrentOpenArea] AS [txtCurrentOpenArea],
            [F].[txtApprovedOpenArea] AS [txtApprovedOpenArea],
            [F].[txtClosureAmount] AS [txtClosureAmount],
            [F].[txtPostClosureCareAmount] AS [txtPostClosureCareAmount],
            [F].[txtCorrectiveActionAmount] AS [txtCorrectiveActionAmount],
            [F].[txtTotalAssuredCost] AS [txtTotalAssuredCost],
            [F].[txtComments] AS [txtComments]
     FROM [LEMIR_Stage].[dbo].[$grdFinancialAssurance] AS [F]
     WHERE [F].[PermitNumber] = [MFI].[MainPermitNumber] FOR XML PATH('grdFinancialAssurance')), '') AS [grdFinancialAssurance],
     --
       isnull(
    (SELECT DISTINCT
            convert(VARCHAR(50), [C].[txtAcceptingWasteCeasedDate], 101) AS [txtAcceptingWasteCeasedDate],
            [C].[txtPhaseCell] AS [txtPhaseCell],
            convert(VARCHAR(50), [C].[txtClosurePermitIssuedDate], 101) AS [txtClosurePermitIssuedDate]
     FROM [LEMIR_Stage].[dbo].[$grdClosure] AS [C]
     WHERE [C].[PermitNumber] = [MFI].[MainPermitNumber] FOR XML PATH('grdClosure')), '') AS [grdClosure],
     --
       isnull(
    (SELECT DISTINCT
            convert(VARCHAR(50), [C].[txtApprovedDate], 101) AS [txtApprovedDate],
            [C].[txtPhase] AS [txtPhase],
            [C].[txtCell] AS [txtCell]
     FROM [LEMIR_Stage].[dbo].[$grdConstructionDetail] AS [C]
     WHERE [C].[PermitNumber] = [MFI].[MainPermitNumber] FOR XML PATH('grdConstructionDetail')), '') AS [grdConstructionDetail],
     --
       isnull(
    (SELECT DISTINCT
            convert(VARCHAR(50), [M].[txtMajorModificationIssuedDate], 101) AS [txtMajorModificationIssuedDate],
            [M].[txtMajorModificationPurpose] AS [txtMajorModificationPurpose]
     FROM [LEMIR_Stage].[dbo].[$grdMajorModification] AS [M]
     WHERE [M].[PermitNumber] = [MFI].[MainPermitNumber] FOR XML PATH('grdMajorModification')), '') AS [grdMajorModification],
     --
       [FACILITY_ID_REF]=CASE
                           WHEN [MFI].[MainPermitNumber] LIKE '0%'
                             THEN(SUBSTRING([MFI].[MainPermitNumber], 0, 8))
                           WHEN [MFI].[MainPermitNumber] LIKE '1%'
                             THEN(SUBSTRING([MFI].[MainPermitNumber], 0, 8))
                           WHEN [MFI].[MainPermitNumber] LIKE 'APL %'
                             THEN '400-'+substring([MFI].[MainPermitNumber], 5, 20)
                           WHEN [MFI].[MainPermitNumber] LIKE 'APL0%'
                             THEN '400-'+substring([MFI].[MainPermitNumber], 5, 20)
                           WHEN [MFI].[MainPermitNumber] LIKE 'APL-%'
                             THEN '400-'+substring([MFI].[MainPermitNumber], 5, 20)
                           WHEN [MFI].[MainPermitNumber] LIKE 'APLI%'
                             THEN '400-'+substring([MFI].[MainPermitNumber], 5, 20)
                           WHEN [MFI].[MainPermitNumber] LIKE 'APL1%'
                             THEN '400-'+substring([MFI].[MainPermitNumber], 5, 20)
                           WHEN [MFI].[MainPermitNumber] LIKE 'B%'
                             THEN '0'
                           WHEN [MFI].[MainPermitNumber] LIKE 'CCR%'
                             THEN '500-'+[MFI].[MainPermitNumber]
                           WHEN [MFI].[MainPermitNumber] LIKE 'CON%'
                             THEN '600-'+[MFI].[MainPermitNumber]
                           WHEN [MFI].[MainPermitNumber] LIKE 'MOD%'
                             THEN '700-'+[MFI].[MainPermitNumber]
                           WHEN [MFI].[MainPermitNumber] LIKE 'PCSP%'
                             THEN '800-'+[MFI].[MainPermitNumber]
                           ELSE '0'
                         END
FROM [LandDataBase].[dbo].[MAIN FACILITY INFO] AS [MFI]
GO


