
/*****************************************************
*** Insert into LEMIR_Stage values for EI "MM" XML ***
*****************************************************/

--
USE [LEMIR_Stage]
GO
--
--INSERT INTO [dbo].[EI_MM]
--       ([PermitNumber],
--        [EnvIntType],
--        [ucontrolGeologist_ID],
--        [ucontrolGeologist_VAL],
--        [ucontrolGeologist_TAG],
--        [ucontrolGeologist_VIS],
--        [ucontrolGeologist_HIS],
--        [ucontrolGeologist_DES],
--        [ucontrolGeologist_COM],
--        [ucontrolComplianceStatus_ID],
--        [ucontrolComplianceStatus_VAL],
--        [ucontrolComplianceStatus_TAG],
--        [ucontrolComplianceStatus_VIS],
--        [ucontrolComplianceStatus_HIS],
--        [ucontrolComplianceStatus_DES],
--        [ucontrolComplianceStatus_COM],
--        [ucontrolMilestone_ID],
--        [ucontrolMilestone_VAL],
--        [ucontrolMilestone_TAG],
--        [ucontrolMilestone_VIS],
--        [ucontrolMilestone_HIS],
--        [ucontrolMilestone_DES],
--        [ucontrolMilestone_COM],
--        [ucontrolSubmittal_ID],
--        [ucontrolSubmittal_VAL],
--        [ucontrolSubmittal_TAG],
--        [ucontrolSubmittal_VIS],
--        [ucontrolSubmittal_HIS],
--        [ucontrolSubmittal_DES],
--        [ucontrolSubmittal_COM],
--        [ucontrolAttachment_ID],
--        [ucontrolAttachment_VAL],
--        [ucontrolAttachment_TAG],
--        [ucontrolAttachment_VIS],
--        [ucontrolAttachment_HIS],
--        [ucontrolAttachment_DES],
--        [ucontrolAttachment_COM],
--        [ddlGeologist_ID],
--        [ddlGeologist_VAL],
--        [ddlGeologist_TAG],
--        [ddlGeologist_VIS],
--        [ddlGeologist_HIS],
--        [ddlGeologist_DES],
--        [ddlGeologist_COM],
--        [ddlComplianceStatus_ID],
--        [ddlComplianceStatus_VAL],
--        [ddlComplianceStatus_TAG],
--        [ddlComplianceStatus_VIS],
--        [ddlComplianceStatus_HIS],
--        [ddlComplianceStatus_DES],
--        [ddlComplianceStatus_COM],
--        [FACILITY_ID_REF])
SELECT [PermitNumber],
       [EnvIntType],
       [ucontrolGeologist_ID],
       [ucontrolGeologist_VAL],
       [ucontrolGeologist_TAG],
       [ucontrolGeologist_VIS],
       [ucontrolGeologist_HIS],
       [ucontrolGeologist_DES],
       [ucontrolGeologist_COM],
       [ucontrolComplianceStatus_ID],
       [ucontrolComplianceStatus_VAL],
       [ucontrolComplianceStatus_TAG],
       [ucontrolComplianceStatus_VIS],
       [ucontrolComplianceStatus_HIS],
       [ucontrolComplianceStatus_DES],
       [ucontrolComplianceStatus_COM],
       [ucontrolMilestone_ID],
       [ucontrolMilestone_VAL],
       [ucontrolMilestone_TAG],
       [ucontrolMilestone_VIS],
       [ucontrolMilestone_HIS],
       [ucontrolMilestone_DES],
       [ucontrolMilestone_COM],
       [ucontrolSubmittal_ID],
       [ucontrolSubmittal_VAL],
       [ucontrolSubmittal_TAG],
       [ucontrolSubmittal_VIS],
       [ucontrolSubmittal_HIS],
       [ucontrolSubmittal_DES],
       [ucontrolSubmittal_COM],
       [ucontrolAttachment_ID],
       [ucontrolAttachment_VAL],
       [ucontrolAttachment_TAG],
       [ucontrolAttachment_VIS],
       [ucontrolAttachment_HIS],
       [ucontrolAttachment_DES],
       [ucontrolAttachment_COM],
       [ddlGeologist_ID],
       [ddlGeologist_VAL],
       [ddlGeologist_TAG],
       [ddlGeologist_VIS],
       [ddlGeologist_HIS],
       [ddlGeologist_DES],
       [ddlGeologist_COM],
       [ddlComplianceStatus_ID],
       [ddlComplianceStatus_VAL],
       [ddlComplianceStatus_TAG],
       [ddlComplianceStatus_VIS],
       [ddlComplianceStatus_HIS],
       [ddlComplianceStatus_DES],
       [ddlComplianceStatus_COM],
       [FACILITY_ID_REF]
FROM [dbo].[EI_MM]  -- insert correct DB name and values
GO