USE [master]
GO

/****** Object:  Database [LEMIR_Stage_Out]    Script Date: 12/19/2018 3:17:52 PM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'LEMIR_Stage_Out')
BEGIN
CREATE DATABASE [LEMIR_Stage_Out]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LEMIR_Stage_Out', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLTOM\MSSQL\DATA\LEMIR_Stage_Out.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LEMIR_Stage_Out_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLTOM\MSSQL\DATA\LEMIR_Stage_Out_log.ldf' , SIZE = 1792KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END
GO

ALTER DATABASE [LEMIR_Stage_Out] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LEMIR_Stage_Out].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LEMIR_Stage_Out] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET ARITHABORT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET RECOVERY FULL 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET  MULTI_USER 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LEMIR_Stage_Out] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LEMIR_Stage_Out] SET  READ_WRITE 
GO


