USE [GovOnline_LEMIR]
GO

/****** Object:  Table [dbo].[SYS_DISPOSAL]    Script Date: 1/17/2019 2:14:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SYS_DISPOSAL](
	[SYS_DISPOSAL_RID] [int] NOT NULL,
	[FACILITY_RID] [int] NOT NULL,
	[REPORTING_YEAR] [int] NULL,
	[REPORTING_QUARTER] [varchar](50) NULL,
	[SUBMISSION_RID] [int] NULL,
	[INIT_DISPOSAL_AMOUNT] [decimal](12, 2) NULL,
	[INIT_RECYCLED_AMOUNT] [decimal](12, 2) NULL,
	[DISPOSAL_AMOUNT] [decimal](12, 2) NULL,
	[RECYCLED_AMOUNT] [decimal](12, 2) NULL,
	[SUB_FEE_RID] [int] NULL,
	[FEE_AMOUNT] [decimal](12, 2) NULL,
	[SYN_DATE] [datetime] NULL,
	[SENT_BY] [varchar](100) NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
	[CHANGED_IND] [varchar](10) NULL,
 CONSTRAINT [PK_SYS_DISPOSAL] PRIMARY KEY CLUSTERED 
(
	[SYS_DISPOSAL_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__257252FF]  DEFAULT ('A') FOR [STATUS_CD]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__CREAT__26667738]  DEFAULT ('SYSTEM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__CREAT__284EBFAA]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__UPDAT__275A9B71]  DEFAULT ('SYSTEM') FOR [UPDATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__UPDAT__2942E3E3]  DEFAULT (getdate()) FOR [UPDATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_FAC_FACILITY] FOREIGN KEY([FACILITY_RID])
REFERENCES [dbo].[FAC_FACILITY] ([FACILITY_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] CHECK CONSTRAINT [FK_SYS_DISPOSAL_FAC_FACILITY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_SUB_FEE] FOREIGN KEY([SUB_FEE_RID])
REFERENCES [GOV].[SUB_FEE] ([SUB_FEE_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] CHECK CONSTRAINT [FK_SYS_DISPOSAL_SUB_FEE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_SUB_SUBMISSION] FOREIGN KEY([SUBMISSION_RID])
REFERENCES [GOV].[SUB_SUBMISSION] ([SUBMISSION_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] CHECK CONSTRAINT [FK_SYS_DISPOSAL_SUB_SUBMISSION]
GO


/****** Object:  Table [dbo].[SYS_DISPOSAL_HISTORY]    Script Date: 1/17/2019 2:14:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SYS_DISPOSAL_HISTORY](
	[SYS_DISPOSAL_HISTORY_RID] [int] NOT NULL,
	[SYS_DISPOSAL_RID] [int] NOT NULL,
	[ORIGINAL_DISPOSAL_AMOUNT] [decimal](12, 2) NOT NULL,
	[REVISED_DISPOSAL_AMOUNT] [decimal](12, 2) NOT NULL,
	[ORIGINAL_RECYCLED_AMOUNT] [decimal](12, 2) NOT NULL,
	[REVISED_RECYCLED_AMOUNT] [decimal](12, 2) NOT NULL,
	[COMMENT_TEXT] [varchar](4000) NULL,
	[SUB_FEE_RID] [int] NULL,
	[SYN_DATE] [datetime] NULL,
	[SENT_BY] [varchar](100) NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
	[REVISED_DATE] [datetime] NULL,
	[REVISED_BY] [varchar](100) NULL,
	[BATCH_TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_SYS_DISPOSAL_HISTORY] PRIMARY KEY CLUSTERED 
(
	[SYS_DISPOSAL_HISTORY_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__257252FF]  DEFAULT ('A') FOR [STATUS_CD]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY_CREAT__26667738]  DEFAULT ('SYSTEM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__CREAT__284EBFAA]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY__UPDAT__275A9B71]  DEFAULT ('SYSTEM') FOR [UPDATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] ADD  CONSTRAINT [DF__SYS_DISPOSAL_HISTORY_2942E3E3]  DEFAULT (getdate()) FOR [UPDATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SUB_FEE] FOREIGN KEY([SUB_FEE_RID])
REFERENCES [GOV].[SUB_FEE] ([SUB_FEE_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] CHECK CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SUB_FEE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SYS_DISPOSAL] FOREIGN KEY([SYS_DISPOSAL_RID])
REFERENCES [dbo].[SYS_DISPOSAL] ([SYS_DISPOSAL_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL_HISTORY] CHECK CONSTRAINT [FK_SYS_DISPOSAL_HISTORY_SYS_DISPOSAL]
GO



