USE [LEMIR_SO_fixes]
GO

INSERT INTO [dbo].[PMT_PERMIT]
           ([PERMIT_RID]
           ,[PERMIT_NO]
           ,[FACILITY_RID]
         ,[PERMIT_TYPE_RID]
--           ,[EFF_DATE]
          
--           ,[DRAFT_ISSUE_DATE]
           ,[ISSUE_DATE]
            ,[EXP_DATE]
--           ,[REVOKED_DATE]
--           ,[RENEWAL_DATE]
--           ,[RENEWAL_REMIND_DATE]
           --,[APPROVE_DATE]
           ,[APPROVED_BY]
           ,[REPORT_FREQUENCY_RID]

--           ,[PERMIT_STATUS_CHANGE_REASON]
           ,[PARENT_PERMIT_RID]
           ,[ASSOCIATED_PREVIOUS_PERMIT_RID]
--           ,[ESUBMISSION_IND]
--           ,[DEFAULT_DURATION]
--           ,[DEFAULT_DURATION_UNIT]
           ,[STATUS_CD]
                      ,[COMMENT_TEXT]
           ,[CREATED_DATE]
           ,[CREATED_BY]
           ,[UPDATED_DATE]
           ,[UPDATED_BY]
                      ,[PERMIT_STATUS_RID]
--           ,[PERMIT_XML]

--           ,[PERMIT_NAME]
           ,[PROGRAM_TYPE_RID]
--           ,[STATE_PERMIT_ID]
--           ,[PERMIT_VERSION]
--           ,[TERMINATE_DATE]
--           ,[PERMITTEE_NAME]
--           ,[EXTENDED_EXP_DATE]
--           ,[AGGREGATED_IND]
--           ,[NRCCWPI_PERMIT_INSTANCE_ID]
--           ,[PMT_CONTINUOUS_IND]
--           ,[PMT_EXTENDED_DATE]
--           ,[IPACS_PMT_ID]
--           ,[IPACS_SUBMISSION_RID]
--           ,[RENEW_PERMIT_IND]
--           ,[EXCHANGE_PERMIT_RID])
)
    SELECT [PERMIT_RID]
      --,[SUBMISSION_RID]
      --,[SUB_FORM_RID]
      ,[PERMIT_NUMBER]
      --,[SYS_USER_RID]
      ,[SYS_FACILITY_ID]
      --,[FACILITY_NAME]
      --,[ISSUED_BY]
      ,[ISSUED_DTTM]
      --,[EFFECTIVE_DTTM]
      ,[EXPIRATION_DTTM]
      ,[STATUS_CD]
      ,[COMMENTS]
      ,[CREATED_DTTM]
      ,[CREATED_BY]
      ,[UPDATED_DTTM]
      ,[UPDATED_BY]
      --,[TRANSFER_TO]
      ,[PERMIT_STATUS_RID]
      ,[PERMIT_TYPE_RID]
      --,[PERMIT_DETAIL]
      --,[PERMIT_NAME]
      --,[REPORT_RID]
      --,[NUMBER_SUFFIX]
      --,[EXPIRATION_DESC]
      --,[BARCODE_IMAGE]
      --,[BARCODE_NUMBER]
      --,[SUB_PRIOR_APPROVAL_RID]
      --,[OBJECT_TYPE]
      --,[DESCRIPTION]
      --,[APPLICATION_RID]
      --,[PERMIT_STAGE_RID]
      --,[CONTROL_NUMBER]
      --,[EXCHANGE_PERMIT_RID]
      --,[OBJECT]
      --,[REVISION_NO]
      --,[CHECK_OUT_BY]
      --,[CHECK_OUT_DATE]
      --,[CHECK_OUT_DIRECTORY]
      --,[VERSION_NO]
      --,[LOCK_IND]
      --,[PERMIT_FILE_NAME]
      --,[EXTRA_INFO]
      --,[PERMIT_FILE_EXT]
      --,[FACILITY_ID_REF]
  FROM [LEMIR_Stage].[GOV].[SUB_PERMIT]
GO


