USE [LEMIR_Stage_Out]   --[LEMIR_Stage]  -- fill this in
GO
DELETE FROM [GOV].[SUB_PERMIT]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[FAC_ENV_PROGRAM_LOC]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[SYS_ENV_PROGRAM_CONTACT_DUTY]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[SYS_ENV_PROGRAM_CONTACT]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[FAC_ENV_PROGRAM]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[FAC_TELEPHONIC]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[SYS_CONTACT_TELEPHONIC]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[SYS_TELEPHONIC]
WHERE [CREATED_BY] = 'EPDMIG SW'
      --AND [TELEPHONIC_RID] > 21640455 --21640673
GO
DELETE FROM [dbo].[FAC_EMAIL]
WHERE [CREATED_BY] = 'EPDMIG SW'
GO
DELETE FROM [dbo].[FAC_ADDRESS]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE ADDRESS_RID > 10717716
GO
DELETE FROM [dbo].[FAC_LOCATION]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE LOCATION_RID > 629088
GO
DELETE FROM [dbo].[FAC_CONTACT]
WHERE [CREATED_BY] = 'EPDMIG SW'
 --where [CONTACT_RID] > 612831
GO
DELETE FROM [dbo].[SYS_CONTACT_EMAIL]
WHERE [CREATED_BY] = 'EPDMIG SW'
 --where [CONTACT_RID] > 612831
GO
DELETE FROM [dbo].[SYS_CONTACT_ADDRESS]
WHERE [CREATED_BY] = 'EPDMIG SW'
 --where [CONTACT_RID] > 612831
GO
DELETE FROM [dbo].[SYS_EMAIL]
WHERE [CREATED_BY] = 'EPDMIG SW'
     --where [EMAIL_RID] > 18465862
GO
DELETE FROM [dbo].[SYS_ADDRESS]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE [ADDRESS_RID] > 10717716

GO
DELETE FROM [dbo].[SYS_CONTACT]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE [CONTACT_RID] > 612831

GO
DELETE FROM [dbo].[SYS_PHYSICAL_LOCATION]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE [LOCATION_RID] > 622746                      --LEMIR UAT3 Location_RID = 622747 to 624244             GEoCoord_RID = Null to 622372 @Loc_RID 622772 then to 623751
GO
DELETE FROM [dbo].[SYS_GEO_COORDINATE]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE [dbo].[SYS_GEO_COORDINATE].[GEO_COORDINATE_RID] > 622346   --LEMIR UAT3  Phys Loc RID = 622772 to 624244
--      AND [dbo].[SYS_GEO_COORDINATE].[GEO_COORDINATE_RID] < 628643
GO
DELETE FROM [dbo].[FAC_FACILITY]
WHERE [CREATED_BY] = 'EPDMIG SW'
--WHERE [dbo].[FAC_FACILITY].[FACILITY_RID] > 336234
--      AND [dbo].[FAC_FACILITY].[FACILITY_RID] < 342499
GO





--[SYS_PHYSICAL_LOCATION] where createdBy = EPDMIG SW = loc RID 621748 to 624244    GEO_COORDS = NULL from 621748  to 622771 --- 50 locations without geocoords (first round test)
