USE [master]
GO

/****** Object:  Database [LEMIR_Stage_Out_OB]    Script Date: 12/19/2018 3:17:52 PM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'LEMIR_Stage_Out_OB')
BEGIN
CREATE DATABASE [LEMIR_Stage_Out_OB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LEMIR_Stage_Out_OB', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLTOM\MSSQL\DATA\LEMIR_Stage_Out_OB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LEMIR_Stage_Out_OB_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLTOM\MSSQL\DATA\LEMIR_Stage_Out_OB_log.ldf' , SIZE = 1792KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LEMIR_Stage_Out_OB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET RECOVERY FULL 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET  MULTI_USER 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LEMIR_Stage_Out_OB] SET  READ_WRITE 
GO


