USE [LEMIR_Stage]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYS_DISPOSAL_SUB_SUBMISSION]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL]'))
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [FK_SYS_DISPOSAL_SUB_SUBMISSION]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYS_DISPOSAL_SUB_FEE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL]'))
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [FK_SYS_DISPOSAL_SUB_FEE]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SYS_DISPOSAL_FAC_FACILITY]') AND parent_object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL]'))
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [FK_SYS_DISPOSAL_FAC_FACILITY]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL__UPDAT__2942E3E3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [DF__SYS_DISPOSAL__UPDAT__2942E3E3]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL__UPDAT__275A9B71]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [DF__SYS_DISPOSAL__UPDAT__275A9B71]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL__CREAT__284EBFAA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [DF__SYS_DISPOSAL__CREAT__284EBFAA]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL__CREAT__26667738]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [DF__SYS_DISPOSAL__CREAT__26667738]
END
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__SYS_DISPOSAL__257252FF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SYS_DISPOSAL] DROP CONSTRAINT [DF__SYS_DISPOSAL__257252FF]
END
GO

/****** Object:  Table [dbo].[SYS_DISPOSAL]    Script Date: 4/23/2019 11:45:49 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYS_DISPOSAL]') AND type in (N'U'))
DROP TABLE [dbo].[SYS_DISPOSAL]
GO

/****** Object:  Table [dbo].[SYS_DISPOSAL]    Script Date: 4/23/2019 11:45:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SYS_DISPOSAL](
	[SYS_DISPOSAL_RID] [int] NOT NULL,
	[FACILITY_RID] [int] NOT NULL,
	[REPORTING_YEAR] [int] NULL,
	[REPORTING_QUARTER] [varchar](50) NULL,
	[SUBMISSION_RID] [int] NULL,
	[INIT_DISPOSAL_AMOUNT] [decimal](12, 2) NULL,
	[INIT_RECYCLED_AMOUNT] [decimal](12, 2) NULL,
	[DISPOSAL_AMOUNT] [decimal](12, 2) NULL,
	[RECYCLED_AMOUNT] [decimal](12, 2) NULL,
	[SUB_FEE_RID] [int] NULL,
	[FEE_AMOUNT] [decimal](12, 2) NULL,
	[SYN_DATE] [datetime] NULL,
	[SENT_BY] [varchar](100) NULL,
	[STATUS_CD] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](100) NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
	[CHANGED_IND] [varchar](10) NULL,
	[FACILITY_TYPE] [varchar](50) NULL,
 CONSTRAINT [PK_SYS_DISPOSAL] PRIMARY KEY CLUSTERED 
(
	[SYS_DISPOSAL_RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__257252FF]  DEFAULT ('A') FOR [STATUS_CD]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__CREAT__26667738]  DEFAULT ('SYSTEM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__CREAT__284EBFAA]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__UPDAT__275A9B71]  DEFAULT ('SYSTEM') FOR [UPDATED_BY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] ADD  CONSTRAINT [DF__SYS_DISPOSAL__UPDAT__2942E3E3]  DEFAULT (getdate()) FOR [UPDATED_DATE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_FAC_FACILITY] FOREIGN KEY([FACILITY_RID])
REFERENCES [dbo].[FAC_FACILITY] ([FACILITY_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] CHECK CONSTRAINT [FK_SYS_DISPOSAL_FAC_FACILITY]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_SUB_FEE] FOREIGN KEY([SUB_FEE_RID])
REFERENCES [GOV].[SUB_FEE] ([SUB_FEE_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] CHECK CONSTRAINT [FK_SYS_DISPOSAL_SUB_FEE]
GO

ALTER TABLE [dbo].[SYS_DISPOSAL]  WITH CHECK ADD  CONSTRAINT [FK_SYS_DISPOSAL_SUB_SUBMISSION] FOREIGN KEY([SUBMISSION_RID])
REFERENCES [GOV].[SUB_SUBMISSION] ([SUBMISSION_RID])
GO

ALTER TABLE [dbo].[SYS_DISPOSAL] CHECK CONSTRAINT [FK_SYS_DISPOSAL_SUB_SUBMISSION]
GO


