USE [LEMIR_Stage_Out]
GO
DELETE FROM [dbo].[SYS_DISPOSAL_HISTORY]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [dbo].[SYS_DISPOSAL]
WHERE [CREATED_BY] = 'EPDMIG SWT'
--
DELETE FROM [GOV].[SUB_SUBMISSION_LEMIR]
WHERE [CREATED_BY] = 'EPDMIG SWT';
--
USE [LEMIR_Stage_Out]
GO
DELETE FROM [GOV].[SUB_SUBMISSION_GEOS]
WHERE [CREATED_BY] = 'EPDMIG SWT';
